import type { ActivityTemplate } from "../prisma/seeds/activities/types";

function a(partial: Omit<ActivityTemplate, "authoring">): ActivityTemplate {
  return { authoring: "HAND_AUTHORED", ...partial };
}

const skin =
  "Bind displayName as Captain. Rho is First Mate. Keep crew names: Bosun Mara, Cook Pell, Scout Idi, Carpenter Vey, Signaler Tem.";

export const elaActivities: ActivityTemplate[] = [
  a({
    slug: "g3-ela-wreck-log-central-idea",
    title: "Torn sailing log: central idea",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.R.2.2"],
    chapterId: "u1-ch1",
    unitId: "u1-crash",
    prompt:
      "Read the torn sailing log. Name the central idea. List two details that support it. Then decide: do we haul the wet charts inland tonight, or pin them under rocks on the beach?",
    scaffoldHints: [
      "The central idea is what the whole page is mostly about — not one shiny sentence.",
      "A supporting detail must actually sit in the text.",
      "Your decision should follow from the details, not from a guess.",
    ],
    answerRubric:
      "Central idea matches the log (wreck + urgent salvage of papers/cargo); two relevant details; decision uses those details.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
    readingText:
      "Sailing log, last readable page. Afternoon. Wind shifted without warning. The hull struck the reef with a sound like a drum. We are on a nameless beach. The mast is down. Charts are wet but not torn. If the tide reaches the crate marked SURVEY, the Guild will say we lost the island before we mapped it. Rho wants the papers moved inland. Bosun Mara wants a count of people first. I think both are right, but water does not wait. Central work before dark: save the survey crate, name who is missing, and do not light a fire where the sailcloth still drips oil. Whoever reads this: the beach looks calm. It is not. The tide line is already chewing the foam near the crate straps.",
  }),
  a({
    slug: "g3-ela-first-night-narrative",
    title: "First-night captain's log",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.1.2"],
    chapterId: "u1-ch1",
    unitId: "u1-crash",
    prompt:
      "Write a personal or fictional narrative of the first night. Use a logical sequence, descriptions, at least one line of dialogue, transitional words, and an ending. You are the captain.",
    scaffoldHints: [
      "Start with the crash or the moment you stood on the sand.",
      "Use words like then, after that, before dark.",
      "End with what the crew will do at dawn — not with 'I woke up.'",
    ],
    answerRubric:
      "Logical sequence; descriptions; dialogue; transitions; ending present. Grade 3 conventions expected, not perfect.",
    storySkinNotes: skin,
    estimatedMinutes: 15,
  }),
  a({
    slug: "g3-ela-ration-rules-features",
    title: "Ration rules: features and structure",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.R.2.1"],
    chapterId: "u1-ch2",
    unitId: "u1-crash",
    prompt:
      "Read the ration leaflet. Name one text feature that helps meaning (heading, bold word, numbered list). Name the text structure: chronology, comparison, or cause/effect. Then decide: do we post the cause/effect warning or the comparison table at the cook tent?",
    scaffoldHints: [
      "A heading tells you what a section is about.",
      "Cause/effect explains why something happens.",
      "Comparison shows how two things are alike or different.",
    ],
    answerRubric: "Correct feature; correct structure with evidence; posting decision uses the structure.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
    readingText:
      "GUILD RATION RULES — Beach Camp\nWhy food spoils (cause and effect): If biscuit tins sit in sun, heat rises. If heat rises, fat in the biscuits turns sour. If biscuits turn sour, the crew gets sick and cannot search inland.\nTwo stores compared: SHADE BARREL — stays cooler, harder to reach at night. SUN TARP — easy to grab, hotter by noon.\nOrder of the first three days: Day 1 count everything. Day 2 split shares. Day 3 check what spoiled.\nBold rule: No one takes a second share until Pell calls 'clear.'",
  }),
  a({
    slug: "g3-ela-persuade-hungry-crew",
    title: "Persuade a hungry crewmate",
    kind: "CREW_DIALOGUE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.1.3"],
    chapterId: "u1-ch2",
    unitId: "u1-crash",
    prompt:
      "Mara wants a second biscuit. Write your opinion. Include reasons supported by details from the ration rules, use a transition, and end with a conclusion. Stay kind. No shouting match.",
    scaffoldHints: [
      "Start with I think / I believe.",
      "Because is a useful transition.",
      "A conclusion restates the opinion without a new fight.",
    ],
    answerRubric: "Clear opinion; at least one sourced reason; transition; conclusion; civil tone.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ela-idi-character-arc",
    title: "Idi's journal: character development",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.R.1.1"],
    chapterId: "u1-ch3",
    unitId: "u1-crash",
    prompt:
      "Explain how Scout Idi develops through the plot. Include traits, feelings, motivations, and a response to a situation. Then decide which search grid Idi should lead, and why that choice fits who Idi has become.",
    scaffoldHints: [
      "A trait is what a character is usually like (careful, proud, curious).",
      "Motivation is why they act.",
      "Development means they are not the same at the end as at the start.",
    ],
    answerRubric:
      "Explains change across the plot with trait/feeling/motivation/response; decision fits the development.",
    storySkinNotes: skin,
    estimatedMinutes: 14,
    readingText:
      "Idi's trail pages, recovered from a thorn bush. Page 1: 'I will not wait for a grid. I am the fastest. Rho worries too much.' Page 2: a sketch of a snapped bootlace and the words 'I was wrong about the ridge. The fog is a wall.' Page 3: 'I sat still until a bird called twice. That is how I found Mara's kerchief. Fast is not the same as useful.' Page 4: 'If the captain lets me lead, I will walk slow on purpose. I want the missing ones found, not my pride.' The last line is smudged. It might say 'sorry' or 'signal.' Rho says we should not invent the smudge.",
  }),
  a({
    slug: "g3-ela-summarize-trail",
    title: "Summarize the trail tale",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.R.3.2"],
    chapterId: "u1-ch3",
    unitId: "u1-crash",
    prompt:
      "Summarize Idi's journal for the search teams. For this literary text, include plot and theme. Keep it shorter than the original.",
    scaffoldHints: [
      "Plot: what happens, in order, without every tiny detail.",
      "Theme: a lesson or big idea the story points toward.",
      "Do not retell every sentence.",
    ],
    answerRubric: "Summary includes plot and theme; concise; accurate to the journal.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ela-merchant-evidence",
    title: "Merchant notice: author's evidence",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.R.2.3"],
    chapterId: "u2-ch4",
    unitId: "u2-camp",
    prompt:
      "Explain what evidence the author uses to support an idea or claim. Then decide: do we trade timber at the posted rate, or wait one day?",
    scaffoldHints: [
      "Evidence might be a number, a comparison, or a result.",
      "An idea without evidence is just a wish.",
      "Your trade decision should cite the evidence you named.",
    ],
    answerRubric: "Identifies an idea/claim and the textual evidence; decision uses that evidence.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
    readingText:
      "NOTICE FROM THE RIVER TRADER\nI have walked this coast before. Last season I took eight coils of rope for four planks and both of us left fed. This week my mule carries salt, not rope. Salt keeps fish. Fish keeps crews. I offer two bags of salt for six sound planks. I do not offer three bags. Three bags emptied my pack when a storm ruined a camp upshore — I watched the barrels bloated and leaking. If your planks are green (still wet inside), I will not trade. Knock a plank on a rock. A dry plank rings. A green plank thuds. That sound is my evidence, not my mood.",
  }),
  a({
    slug: "g3-ela-trade-proposal",
    title: "Write the trade proposal",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.1.4"],
    chapterId: "u2-ch4",
    unitId: "u2-camp",
    prompt:
      "Write an expository trade proposal. Use the merchant notice as a source. Include an introduction, facts and details, some elaboration, transitions, and a conclusion.",
    scaffoldHints: [
      "Introduce what you want to exchange.",
      "Put facts from the notice in the middle, not only your feelings.",
      "Conclude with what happens if both sides agree.",
    ],
    answerRubric: "Expository structure present; uses at least one source fact; transitions; conclusion.",
    storySkinNotes: skin,
    estimatedMinutes: 15,
  }),
  a({
    slug: "g3-ela-storm-briefing-speech",
    title: "Speak the storm bulletin",
    kind: "SPEECH",
    prismaKind: "STORY_SCENE",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.2.1"],
    chapterId: "u2-ch5",
    unitId: "u2-camp",
    prompt:
      "Present the storm plan orally in a logical sequence. Use posture and expressive delivery, appropriate volume, and clear pronunciation. You may read your card, but do not scramble the order.",
    scaffoldHints: [
      "Order: what we know, what we will do, who is on watch.",
      "Stand tall; do not whisper.",
      "If you mix up the order, self-correct and continue.",
    ],
    answerRubric: "Logical sequence; audible; pronunciation care; nonverbal cues attempted.",
    storySkinNotes: skin + " STT/TTS: child may speak; Rho does not give the speech for them.",
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-ela-context-clues-bulletin",
    title: "Storm words in context",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.V.1.3"],
    chapterId: "u2-ch5",
    unitId: "u2-camp",
    prompt:
      "Use context clues, word relationships, or background knowledge to define multiple-meaning and unknown words in the bulletin.",
    scaffoldHints: [
      "Read the whole sentence, not just the hard word.",
      "Front can mean the front of a tent or a weather front.",
      "A glossary in the wreck library is a reference material.",
    ],
    answerRubric: "Meanings fit the bulletin context; distinguishes multiple-meaning uses.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "'A cold front will cross the ridge.' What does front mean here?",
        choices: ["The doorway of a tent", "A moving edge of weather", "A person's face", "To pay money"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "The bulletin says the tide will 'chew' the beach. The best meaning is —",
        choices: ["eat with teeth", "wear away the sand", "cook the sand", "hide the sand"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt:
          "In 'secure the lines,' does secure mean 'safe' or 'tie down'? Use a clue from this sentence: 'Secure the lines to the stakes so the sailcloth does not fly.'",
        sampleAnswer: "Tie down; the phrase 'to the stakes' shows an action, not a feeling.",
      },
    ],
  }),
  a({
    slug: "g3-ela-water-claim",
    title: "Water leaflet: claim and evidence",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.R.2.4"],
    chapterId: "u2-ch6",
    unitId: "u2-camp",
    prompt:
      "Identify the author's claim. Explain how evidence supports it. Then decide: drink from the spring today, boil first, or keep walking.",
    scaffoldHints: [
      "A claim is what the author wants you to believe.",
      "Evidence might be a test, a comparison, or a result.",
      "Your decision should follow the claim only if the evidence is strong.",
    ],
    answerRubric: "Claim identified; evidence explained; decision tied to evidence quality.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
    readingText:
      "WATER SAFETY — unsigned leaflet from the survey crate\nClaim: Clear water is not always safe water.\nEvidence: In three beach camps last year, crews who drank from bright, pretty pools got stomach cramps by night. Crews who boiled the same water for as long as it takes to sing two slow songs did not. The writer also notes that water under leaves can look brown and still be safer after boiling than sparkling water that sat in sun with insects. The leaflet does not name the camps. Rho says an unsigned page is still a source, but a weaker one. Pell says smell is not listed as evidence here, so we should not add it.",
  }),
  a({
    slug: "g3-ela-spring-research",
    title: "Research: is this spring safe?",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.4.1"],
    chapterId: "u2-ch6",
    unitId: "u2-camp",
    prompt:
      "Conduct research to answer: Is the camp spring safe to drink if we boil it? Organize information from at least two sources (leaflet, Pell's notes, Idi's observations). You do not have to use every source you glance at — choose trustworthy, relevant notes.",
    scaffoldHints: [
      "Write the question at the top.",
      "Make two columns: source name, useful fact.",
      "End with an answer that uses the notes, not a new invention.",
    ],
    answerRubric: "Question answered; information organized from multiple sources; discernment shown.",
    storySkinNotes: skin,
    estimatedMinutes: 15,
  }),
  a({
    slug: "g3-ela-decode-markers",
    title: "Decode the trail markers",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.F.1.3"],
    chapterId: "u3-ch7",
    unitId: "u3-map",
    prompt:
      "Use phonics and word analysis. Decode words with common Greek/Latin roots and affixes. Tell how a suffix like -ful, -less, or -est changes the part of speech. Decode a multisyllabic marker word.",
    scaffoldHints: [
      "re- can mean again, as in rebuild.",
      "-ful can turn a noun into an adjective: care → careful.",
      "Clap syllables in unmapped: un-map-ped.",
    ],
    answerRubric: "Correct decoding; suffix/part-of-speech description; multisyllabic attempt is accurate.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "In rebuild, the prefix re- most nearly means —",
        choices: ["not", "again", "full of", "without"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "Adding -ful to care makes careful, which is —",
        choices: ["a noun naming a person", "an adjective describing how someone acts", "a past-tense verb", "a plural noun"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "Break unmapped into syllables and use it in a captain sentence about the island.",
        sampleAnswer: "un-mapped; We will not walk the unmapped ridge after dark.",
      },
    ],
  }),
  a({
    slug: "g3-ela-fluency-survey-log",
    title: "Read the survey log aloud",
    kind: "SPEECH",
    prismaKind: "STORY_SCENE",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.F.1.4"],
    chapterId: "u3-ch7",
    unitId: "u3-map",
    prompt:
      "Read the grade-level survey paragraph with accuracy, a steady rate, and expression that follows the punctuation. This is a fluency check, not a race.",
    scaffoldHints: [
      "Pause at commas and periods.",
      "If you stumble, go back to the start of the sentence.",
      "Expression means you sound like you understand, not like a robot.",
    ],
    answerRubric: "Accuracy and prosody appropriate to grade-level text; not scored only on speed.",
    storySkinNotes: skin,
    estimatedMinutes: 6,
    readingText:
      "Survey note, inland. The ridge path bends left after the split rock. Do not take the right fork; it drops toward a wet shelf that looks like a road and is not. Mark the split rock with a strip of sailcloth so the next party does not argue. If fog sits on the trees, wait. Waiting is mapping too.",
  }),
  a({
    slug: "g3-ela-cove-theme",
    title: "Theme of the cove tale",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.R.1.2"],
    chapterId: "u3-ch8",
    unitId: "u3-map",
    prompt:
      "Explain a theme and how it develops, using details. Then decide: do we name the cove 'Pell's Bowl' or keep the old marker name 'Quiet Teeth'?",
    scaffoldHints: [
      "Theme is a big idea, not the whole plot.",
      "Pick details that grow that idea.",
      "The name you choose should fit the theme you named.",
    ],
    answerRubric: "Theme stated; details show development; naming decision connects to theme.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
    readingText:
      "Mara's cove tale, told at the fire. A fisher once shouted at the water for hiding fish. The cove stayed still. The fisher sat, quiet, and watched the light change. Fish came when the shouting stopped. Pell laughs at the ending: 'So we should starve politely?' Mara says the tale is not about starving. It is about a place that does not answer noise. Idi says the theme is patience, because every time a character rushes, the cove 'closes.' Rho says we should not pretend the island is a person — but the tale still treats it like one, and that is how the theme shows up.",
  }),
  a({
    slug: "g3-ela-two-perspectives",
    title: "Pell and Mara on the same cove",
    kind: "CREW_DIALOGUE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.R.1.3"],
    chapterId: "u3-ch8",
    unitId: "u3-map",
    prompt:
      "Explain different characters' perspectives (their attitudes), not the narrator's point of view. Then decide whose warning the search party should print on the map.",
    scaffoldHints: [
      "Perspective is how a character regards something.",
      "Pell may see food; Mara may see danger.",
      "Quote or paraphrase each attitude.",
    ],
    answerRubric: "Two perspectives explained with text; map decision names whose attitude is used and why.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ela-cursive-blueprint",
    title: "Cursive labels on the tower blueprint",
    kind: "CREATIVE_PROJECT",
    prismaKind: "CHALLENGE",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.1.1"],
    chapterId: "u3-ch9",
    unitId: "u3-map",
    prompt:
      "Write all upper- and lowercase cursive letters at least once by labeling the blueprint: NORTH, south, Deck, rope, Vey. A model alphabet is on screen. Rain-smear is not an excuse to print.",
    scaffoldHints: [
      "Follow the model strokes.",
      "Keep letters sitting on the line.",
      "Uppercase and lowercase both required.",
    ],
    answerRubric: "Attempted cursive for all requested upper- and lowercase letters; recognizable with a model.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ela-tower-multimedia",
    title: "Two media for the tower plan",
    kind: "CREATIVE_PROJECT",
    prismaKind: "CHALLENGE",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.5.1"],
    chapterId: "u3-ch9",
    unitId: "u3-map",
    prompt:
      "Use two or more multimedia elements to enhance the tower briefing: for example a drawing of the deck and a short recorded audio warning. They should relate directly to the plan.",
    scaffoldHints: [
      "Multimedia can be a picture, a labeled diagram, or audio.",
      "The pieces should help someone understand the plan.",
      "They do not have to be fancy — they have to fit.",
    ],
    answerRubric: "At least two relevant multimedia elements tied to the oral/written task.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ela-revise-charter",
    title: "Revise the camp charter",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.1.5"],
    chapterId: "u4-ch10",
    unitId: "u4-charter",
    prompt:
      "Improve the charter by planning, revising, and editing. Use Rho's adult guidance notes and one peer comment from Mara. You do not have to change every sentence — change what is needed.",
    scaffoldHints: [
      "Plan: list the three rules worth keeping.",
      "Revise: fix unclear meaning.",
      "Edit: spelling and punctuation last.",
    ],
    answerRubric: "Shows planning and at least one meaningful revision plus an edit, responding to feedback.",
    storySkinNotes: skin,
    estimatedMinutes: 15,
  }),
  a({
    slug: "g3-ela-conventions-edit",
    title: "Edit the muster draft",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.3.1"],
    chapterId: "u4-ch10",
    unitId: "u4-charter",
    prompt:
      "Follow grade-level conventions: verb tense, irregular plurals, quotation marks in dialogue, commas for direct address. Fix the muster draft.",
    scaffoldHints: [
      "Keep the same tense in a paragraph.",
      "Commas: 'Rho, hold the line.'",
      "Dialogue: \"We wait,\" said Mara.",
    ],
    answerRubric: "Corrects targeted convention skills from the Grade 3 list; not every advanced skill must appear.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Choose the correct sentence.",
        choices: [
          "Yesterday the crew walk to the spring and fills the pots.",
          "Yesterday the crew walked to the spring and filled the pots.",
          "Yesterday the crew walked to the spring and fill the pots.",
          "Yesterday the crew walks to the spring and filled the pots.",
        ],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "Which uses a comma for direct address?",
        choices: ["Let's eat Pell.", "Let's eat, Pell.", "Lets eat Pell.", "Let's, eat Pell"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: 'Punctuate this dialogue: Mara said we should wait until the fog lifts',
        sampleAnswer: 'Mara said, "We should wait until the fog lifts."',
      },
    ],
  }),
  a({
    slug: "g3-ela-digital-slate",
    title: "Plan and revise on the digital slate",
    kind: "CREATIVE_PROJECT",
    prismaKind: "CHALLENGE",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.5.2"],
    chapterId: "u4-ch10",
    unitId: "u4-charter",
    prompt:
      "Use the in-world digital writing tool (alone or with Rho) to plan, draft, and revise a four-sentence charter clause. Saving versions counts as using the tool.",
    scaffoldHints: [
      "Plan in bullets first.",
      "Draft in full sentences.",
      "Revise after Rho's comment.",
    ],
    answerRubric: "Evidence of plan, draft, and revise in a digital tool.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ela-figurative-share-song",
    title: "Figurative language in the share-song",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.R.3.1"],
    chapterId: "u4-ch11",
    unitId: "u4-charter",
    prompt:
      "Identify and explain metaphors, personification, and hyperbole in the song lines. (Simile may appear from earlier grades but is not the Grade 3 target.)",
    scaffoldHints: [
      "Metaphor says one thing is another.",
      "Personification gives human actions to nonhuman things.",
      "Hyperbole is an exaggeration that is not literal.",
    ],
    answerRubric: "Correct identification and a brief explanation of each targeted type.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "'The loaf was a mountain on Pell's plate.' This is —",
        choices: ["personification", "hyperbole", "a metaphor", "a stage direction"],
        correctIndex: 2,
      },
      {
        itemType: "multiple_choice",
        prompt: "'The wind tugged our sleeves like a bored child' also says the wind tugged. The human action is —",
        choices: ["metaphor only", "personification", "a haiku", "a root word"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "'I could eat a thousand biscuits.' Is that literal? What kind of figurative language is it? Explain.",
        sampleAnswer: "Not literal; hyperbole; exaggerates hunger.",
      },
    ],
  }),
  a({
    slug: "g3-ela-roots-affixes",
    title: "Roots on the share list",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.V.1.2"],
    chapterId: "u4-ch11",
    unitId: "u4-charter",
    prompt:
      "Apply common Greek and Latin roots, base words, and affixes to figure out unfamiliar words on the share list.",
    scaffoldHints: [
      "fract / frac can relate to break (fraction).",
      "un- often means not.",
      "A base word can stand alone; an affix cannot.",
    ],
    answerRubric: "Meanings derived from roots/affixes, not from wild guesses.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "If equal means same, unequal most nearly means —",
        choices: ["more than equal", "not equal", "two equals", "a fraction"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "A fraction names a broken whole. The root idea of 'break' helps you know fraction is about —",
        choices: ["parts of a whole", "a kind of boat", "a loud sound", "a map key"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "The list says 'preheat the kettle.' What does pre- tell you to do, and when?",
        sampleAnswer: "Heat it before; pre- means before.",
      },
    ],
  }),
  a({
    slug: "g3-ela-poem-types",
    title: "Name the island poems",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.R.1.4"],
    chapterId: "u4-ch12",
    unitId: "u4-charter",
    prompt:
      "Identify free verse, rhymed verse, haiku, and limerick in the crew anthology. Match each sample to its type.",
    scaffoldHints: [
      "Haiku is a short 5-7-5 syllable poem.",
      "A limerick is a funny five-line rhymed poem.",
      "Free verse does not have to rhyme.",
    ],
    answerRubric: "Correct identification of all four types.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Five lines, AABBA rhyme, silly last line. Type?",
        choices: ["haiku", "limerick", "free verse", "a table"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "Three lines about fog, 5-7-5 syllables, no forced rhyme. Type?",
        choices: ["limerick", "rhymed verse", "haiku", "a claim"],
        correctIndex: 2,
      },
      {
        itemType: "free_response",
        prompt: "Rho's poem does not rhyme and the line lengths jump. Idi's poem rhymes every two lines. Name each type.",
        sampleAnswer: "Rho: free verse; Idi: rhymed verse.",
      },
    ],
  }),
  a({
    slug: "g3-ela-academic-vocab-remarks",
    title: "Academic words in night remarks",
    kind: "CREW_DIALOGUE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.V.1.1"],
    chapterId: "u4-ch12",
    unitId: "u4-charter",
    prompt:
      "Use grade-level academic vocabulary in speaking or writing. Word bank: compare, evidence, describe, organize, conclude. Write or speak four sentences of captain remarks that use at least three of these words correctly.",
    scaffoldHints: [
      "Academic words work in many subjects.",
      "Do not stuff a word in if it does not fit.",
      "Evidence is something you can point to.",
    ],
    answerRubric: "At least three bank words used appropriately in connected remarks.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-ela-two-authors-spring",
    title: "Two authors, one spring",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.R.3.3"],
    chapterId: "u5-ch13",
    unitId: "u5-guild",
    prompt:
      "Compare and contrast how two authors present information on the same spring. Then decide which page to copy into the Guild packet, or whether both must go.",
    scaffoldHints: [
      "Compare: what is alike.",
      "Contrast: what is different (facts, tone, what they leave out).",
      "You may need both if they cover different evidence.",
    ],
    answerRubric: "Clear compare/contrast of presentation; packet decision is justified.",
    storySkinNotes: skin,
    estimatedMinutes: 14,
    readingText:
      "Author A — Pell: 'The spring tastes of iron. I boiled it. Nobody cramped. I do not care what the leaflet says about pretty water. Taste and a quiet night are my proof.' Author B — Guild leaflet: 'Do not judge water by taste. Boil. Record cloudiness. Last season three camps that trusted taste sent injured crews home.' Both write about the same pool behind our garden. Pell is close and practical. The leaflet is general and warns against Pell's kind of proof. Neither mentions salt. Rho wants both pages in the packet so the inspector cannot say we hid a disagreement.",
  }),
  a({
    slug: "g3-ela-atlas-expository",
    title: "Atlas brief: North America",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.1.4"],
    chapterId: "u5-ch14",
    unitId: "u5-guild",
    prompt:
      "Write an expository page from the Guild atlas (Earth memory). Introduction, facts, elaboration, transitions, conclusion. Do not invent island countries.",
    scaffoldHints: [
      "Start by telling the reader this is Earth geography from a found book.",
      "Use atlas facts, not camp nicknames.",
      "Conclude with why the Guild wants this in the file.",
    ],
    answerRubric: "Expository structure; source-based Earth facts; no distortion of geography into island fiction.",
    storySkinNotes: skin + " Setting: wreck library / Guild atlas.",
    estimatedMinutes: 15,
  }),
  a({
    slug: "g3-ela-civics-opinion",
    title: "Opinion: why voting matters",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.1.3"],
    chapterId: "u5-ch16",
    unitId: "u5-guild",
    prompt:
      "Write an opinion about voting as a civic responsibility, using details from the sealed civics folio (U.S. republic). Camp show-of-hands may be a comparison, but it does not replace the folio.",
    scaffoldHints: [
      "State your opinion in the first sentence.",
      "Use because / also / therefore.",
      "Cite the folio, not only camp feelings.",
    ],
    answerRubric: "Opinion with sourced reasons, transitions, conclusion; honest to SS.3.CG.2.2 content.",
    storySkinNotes: skin + " Setting: wreck library civics folio.",
    estimatedMinutes: 15,
  }),
  a({
    slug: "g3-ela-market-opinion",
    title: "Opinion on the trader's second offer",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.1.3"],
    chapterId: "u6-ch17",
    unitId: "u6-enterprise",
    prompt:
      "Should we accept the trader's second offer? Opinion with reasons from the ledger, transitions, conclusion. This keeps C.1.3 practiced in enterprise, not only in the civics folio.",
    scaffoldHints: [
      "Quote a number from the ledger.",
      "Name a risk.",
      "Conclude with yes, no, or wait.",
    ],
    answerRubric: "Complete opinion structure; ledger details present.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ela-hull-revise",
    title: "Revise the hull plan",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.C.1.4", "ELA.3.C.1.5"],
    chapterId: "u6-ch18",
    unitId: "u6-enterprise",
    prompt:
      "Write an expository hull plan, then revise it after Vey's note: 'You skipped the wet-wood warning.' Show planning, a draft, and an edit.",
    scaffoldHints: [
      "Introduction: what we are building.",
      "Facts: measurements and wood properties.",
      "Revise the missing warning; then edit commas.",
    ],
    answerRubric: "Expository piece plus visible revision from feedback. C.1.4 and C.1.5 both evidenced; each also has a dedicated activity elsewhere.",
    storySkinNotes: skin,
    estimatedMinutes: 18,
  }),
  a({
    slug: "g3-ela-captain-report",
    title: "Guild report with claims and speech",
    kind: "SPEECH",
    prismaKind: "STORY_SCENE",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.R.2.4", "ELA.3.C.2.1", "ELA.3.C.5.1"],
    chapterId: "u6-ch19",
    unitId: "u6-enterprise",
    prompt:
      "Identify a claim in your own report and the evidence that supports it. Present the summary orally in sequence. Include two multimedia elements (map sketch + audio or drawing).",
    scaffoldHints: [
      "A claim might be 'the spring is usable if boiled.'",
      "Point to a chart or a log page as evidence.",
      "Speak in order: wreck, camp, map, report.",
    ],
    answerRubric: "Claim+evidence; oral sequence; two multimedia elements. R.2.4 also has a dedicated reading activity.",
    storySkinNotes: skin,
    estimatedMinutes: 15,
  }),
  a({
    slug: "g3-ela-island-book-excerpt",
    title: "Found book: The Quiet Compass (excerpt)",
    kind: "ISLAND_BOOK",
    prismaKind: "READING",
    subjectSlug: "ela_g3",
    targetStandardCodes: ["ELA.3.R.3.2", "ELA.3.R.1.2"],
    chapterId: "u3-ch8",
    unitId: "u3-map",
    prompt:
      "This is a short found-book excerpt, not a novel. Summarize (plot + theme). Then decide whether the crew should keep the book in the library or use its pages for kindling — and defend the choice with the theme.",
    scaffoldHints: [
      "A summary is shorter than the passage.",
      "Theme is the idea underneath the plot.",
      "Kindling would destroy a source. Say if that matters.",
    ],
    answerRubric: "Literary summary with plot and theme; decision uses the theme. Both codes also have dedicated activities.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
    readingText:
      "From a salt-stained children's book in the wreck library. A young mapmaker named Lin lost a compass overboard and tried to steer by pride. The crew grew hungry. Lin sat on a crate and admitted the loss. An older sailor lent a spare compass, but only after Lin copied the coast by eye, slowly. The last line: 'A true map is a kind of apology you can hold.' Rho says we should not pretend Lin is you, Captain. It is still a story about admitting a mistake before the map is trusted.",
  }),
];
