import type { ActivityTemplate } from "../prisma/seeds/activities/types";

function a(partial: Omit<ActivityTemplate, "authoring">): ActivityTemplate {
  return { authoring: "HAND_AUTHORED", ...partial };
}

const skin = "Bind displayName as Captain. Rho speaks as First Mate. Location: wreck beach unless noted.";

export const mathActivities: ActivityTemplate[] = [
  a({
    slug: "g3-ma-wreck-number-forms",
    title: "Wreck count in three forms",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.NSO.1.1"],
    chapterId: "u1-ch1",
    unitId: "u1-crash",
    prompt:
      "Captain, Rho scraped numbers off crate lids. Write each salvage count in standard form, expanded form, and word form so the Guild can read it later.",
    scaffoldHints: [
      "Standard form is digits, like 2,406.",
      "Expanded form adds place values: 2,000 + 400 + 6.",
      "Word form writes the number in words.",
    ],
    answerRubric:
      "Each number 0–10,000 is correctly shown in all three forms; place-value commas are acceptable.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Crate A is labeled two thousand four hundred six. Which is standard form?",
        choices: ["246", "2,046", "2,406", "24,006"],
        correctIndex: 2,
      },
      {
        itemType: "multiple_choice",
        prompt: "Which is expanded form for 3,070?",
        choices: ["3 + 7 + 0", "3,000 + 70", "300 + 70", "3,000 + 700"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "Write 5,109 in expanded form and in word form.",
        sampleAnswer: "5,000 + 100 + 9; five thousand one hundred nine",
      },
    ],
  }),
  a({
    slug: "g3-ma-compose-crates",
    title: "Compose and break the salvage total",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.NSO.1.2"],
    chapterId: "u1-ch1",
    unitId: "u1-crash",
    prompt:
      "The same pile can be packed different ways. Show 2,340 as thousands, hundreds, tens, and ones in at least two ways. Use drawings or equations (for example 23 hundreds + 4 tens).",
    scaffoldHints: [
      "2,340 is 2 thousands, 3 hundreds, 4 tens.",
      "You can trade 1 thousand for 10 hundreds.",
      "Write an equation for each packing.",
    ],
    answerRubric:
      "At least two correct compositions/decompositions of a four-digit number using thousands–ones; objects, drawings, or equations present.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ma-ration-equal-groups",
    title: "Equal groups of biscuit tins",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.NSO.2.2"],
    chapterId: "u1-ch2",
    unitId: "u1-crash",
    prompt:
      "Cook Pell has 24 biscuits. Show 24 as equal groups (arrays or piles). Write a multiplication equation and a related division equation. Factors stay within 12.",
    scaffoldHints: [
      "6 groups of 4 is 6 × 4 = 24.",
      "Division asks how many in each group or how many groups.",
      "Draw the array so Rho can check.",
    ],
    answerRubric:
      "Correct equal-groups or array model; matching multiplication and related division; product ≤ 144; factors ≤ 12.",
    storySkinNotes: skin + " Location: supply tarp.",
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ma-even-odd-flasks",
    title: "Pair the water flasks",
    kind: "CREW_DIALOGUE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.AR.3.1"],
    chapterId: "u1-ch2",
    unitId: "u1-crash",
    prompt:
      "Rho: 'If we pair flasks, leftover means odd.' Decide whether 18, 47, 200, and 1,000 are even or odd. Explain one answer using place value (look at the ones digit).",
    scaffoldHints: [
      "Even numbers make pairs with none left.",
      "If the ones digit is 0, 2, 4, 6, or 8, the number is even.",
      "1,000 ends in 0, so it is even.",
    ],
    answerRubric:
      "Correct even/odd for each; explanation uses pairing or ones-digit/place value. Range may include 1–1,000.",
    storySkinNotes: skin,
    estimatedMinutes: 7,
  }),
  a({
    slug: "g3-ma-search-grid-tens",
    title: "Paces of tens and hundreds",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.NSO.2.3"],
    chapterId: "u1-ch3",
    unitId: "u1-crash",
    prompt:
      "Each search square is 10 paces on a side. Idi needs products of a one-digit number times 10s or 100s so the grid math is fast.",
    scaffoldHints: [
      "7 × 10 is 7 tens.",
      "4 × 200 is 4 groups of 2 hundreds.",
      "Think of 6 × 80 as 6 × 8 tens.",
    ],
    answerRubric: "Correct products; procedural reliability, not a single required algorithm.",
    storySkinNotes: skin + " Location: inland trailhead.",
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "6 parties × 10 paces = ?",
        choices: ["16", "60", "600", "6,010"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "3 × 400 = ?",
        choices: ["120", "343", "1,200", "12,000"],
        correctIndex: 2,
      },
      {
        itemType: "free_response",
        prompt: "Find 8 × 90. Explain with tens.",
        sampleAnswer: "720; 8 groups of 9 tens is 72 tens.",
      },
    ],
  }),
  a({
    slug: "g3-ma-tent-fact-fluency",
    title: "Tent-row facts through 12",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.NSO.2.4"],
    chapterId: "u1-ch3",
    unitId: "u1-crash",
    prompt:
      "Carpenter Vey is staking tent rows. Multiply two numbers from 0 to 12 and give a related division fact.",
    scaffoldHints: [
      "If 9 × 8 = 72, then 72 ÷ 8 = 9.",
      "0 times anything is 0.",
      "Use a fact you can do reliably — skip-count, array, or known fact.",
    ],
    answerRubric: "Correct products and related division; factors 0–12.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "7 × 8 = ?",
        choices: ["54", "56", "63", "15"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "Which fact is related to 6 × 9 = 54?",
        choices: ["54 ÷ 9 = 6", "54 − 9 = 6", "6 + 9 = 54", "54 × 9 = 6"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "Find 12 × 11 and write one related division equation.",
        sampleAnswer: "132; 132 ÷ 12 = 11 or 132 ÷ 11 = 12",
      },
    ],
  }),
  a({
    slug: "g3-ma-search-cover-area",
    title: "Cover the search rectangle",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.GR.2.1"],
    chapterId: "u1-ch3",
    unitId: "u1-crash",
    prompt:
      "Lay unit squares on a 5-by-8 search rectangle with no gaps or overlaps. Count the squares. Write the area in square units (word form).",
    scaffoldHints: [
      "Area is how many unit squares cover the figure.",
      "No gaps and no overlaps.",
      "Say 'square units' or 'square paces,' not just 40.",
    ],
    answerRubric: "Count 40; unit named in word form; covering model with no gaps/overlaps. Figure ≤ 12×12.",
    storySkinNotes: skin,
    estimatedMinutes: 9,
  }),
  a({
    slug: "g3-ma-camp-add-subtract",
    title: "Timber ledger add and subtract",
    kind: "SPREADSHEET",
    prismaKind: "CHALLENGE",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.NSO.2.1"],
    chapterId: "u2-ch4",
    unitId: "u2-camp",
    prompt:
      "The camp grid has incoming and outgoing timber. Add and subtract multi-digit whole numbers using a method you can do reliably (standard algorithm is welcome).",
    scaffoldHints: [
      "Line up place values.",
      "Regroup when a column is 10 or more, or when you cannot subtract.",
      "Estimate first to see if the answer is reasonable.",
    ],
    answerRubric: "Correct sums and differences for multi-digit items; regrouping shown or described.",
    storySkinNotes: skin + " Bind as camp quartermaster ledger.",
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ma-two-step-budget",
    title: "Two-step camp budget stories",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.AR.1.2"],
    chapterId: "u2-ch4",
    unitId: "u2-camp",
    prompt:
      "Real camp problems hide two steps. Multiplication factors stay within 12. Show what you did first and second.",
    scaffoldHints: [
      "Underline the two questions hiding in the story.",
      "You may add, subtract, multiply, or divide.",
      "Label the answer with what it counts (planks, people, meals).",
    ],
    answerRubric: "Correct two-step solutions; operations match the story; factors ≤ 12 for multiplication/division.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "4 tents hold 6 people each. Then 5 more people arrive. How many people now?",
        choices: ["15", "24", "29", "45"],
        correctIndex: 2,
      },
      {
        itemType: "multiple_choice",
        prompt: "Pell cooks 3 pots of 8 biscuits. The crew eats 10. How many biscuits are left?",
        choices: ["14", "18", "24", "34"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt:
          "Vey has 48 nails. He uses 6 nails on each of 5 boards, then finds 4 extra nails in a jar. How many nails does he have now? Show both steps.",
        sampleAnswer: "6×5=30 used; 48−30=18; 18+4=22 nails.",
      },
    ],
  }),
  a({
    slug: "g3-ma-inventory-pictograph",
    title: "Inventory table and pictograph",
    kind: "SPREADSHEET",
    prismaKind: "CHALLENGE",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.DP.1.1"],
    chapterId: "u2-ch4",
    unitId: "u2-camp",
    prompt:
      "Count four salvage categories. Make a table and a scaled pictograph or bar graph. Give a title, labels, and a key (for example, one crate icon = 2 crates).",
    scaffoldHints: [
      "A scale of 2 means each picture stands for 2.",
      "Title should say what was counted.",
      "Label the categories and the numbers.",
    ],
    answerRubric: "Correct representation of the given data; title, labels, units/key present; whole-number values.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ma-order-tide-counts",
    title: "Order the tide and wind counts",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.NSO.1.3"],
    chapterId: "u2-ch5",
    unitId: "u2-camp",
    prompt:
      "Tem's log has whole numbers up to the thousands. Plot, order, and compare them with <, >, or =.",
    scaffoldHints: [
      "Compare thousands, then hundreds, then tens, then ones.",
      "A number line scaled by 50s or 100s can help.",
      "Equal only if every place matches.",
    ],
    answerRubric: "Correct order and comparison symbols; numbers ≤ 10,000.",
    storySkinNotes: skin + " Location: storm-watch post.",
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Which comparison is true?",
        choices: ["2,085 > 2,805", "2,805 > 2,085", "2,085 = 2,805", "2,805 < 2,080"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "Order least to greatest: 1,040; 1,400; 1,004.",
        choices: ["1,040; 1,004; 1,400", "1,004; 1,040; 1,400", "1,400; 1,040; 1,004", "1,040; 1,400; 1,004"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "Plot 3,250 and 3,500 on a number line scaled by 250s. Write a comparison sentence with < or >.",
        sampleAnswer: "3,250 < 3,500 (or 3,500 > 3,250), points placed reasonably.",
      },
    ],
  }),
  a({
    slug: "g3-ma-watch-clock",
    title: "Tell the watch to the minute",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.M.2.1"],
    chapterId: "u2-ch5",
    unitId: "u2-camp",
    prompt:
      "The analog watch and Tem's digital slate must agree. Tell and write time to the nearest minute. Use a.m. or p.m. (not military time).",
    scaffoldHints: [
      "The short hand is hours; the long hand is minutes.",
      "Each tick is one minute.",
      "Afternoon watches use p.m.",
    ],
    answerRubric: "Times correct to the nearest minute with a.m./p.m.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "The analog clock shows 10:07. The sun is up. How should the log read?",
        choices: ["10:07 a.m.", "10:07 p.m.", "7:10 a.m.", "22:07"],
        correctIndex: 0,
      },
      {
        itemType: "multiple_choice",
        prompt: "Digital slate: 4:53. It is after the midday meal. Choose the written time.",
        choices: ["4:53 a.m.", "4:53 p.m.", "5:43 p.m.", "3:54 p.m."],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "The long hand is on 18 and the short hand is a little past 2 in the afternoon. Write the time.",
        sampleAnswer: "2:18 p.m.",
      },
    ],
  }),
  a({
    slug: "g3-ma-elapsed-storm-prep",
    title: "Elapsed time before the squall",
    kind: "CALCULATOR",
    prismaKind: "CHALLENGE",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.M.2.2"],
    chapterId: "u2-ch5",
    unitId: "u2-camp",
    prompt:
      "Use the in-world calculator if you want, but show the jump of hours and minutes. Do not cross from a.m. to p.m. in these problems.",
    scaffoldHints: [
      "Count hours first, then minutes.",
      "If minutes pass 60, trade 60 minutes for 1 hour.",
      "Stay on the same side of noon.",
    ],
    answerRubric: "Correct end times or elapsed times; no a.m./p.m. crossing required.",
    storySkinNotes: skin + " Offer calculator skin as Tem's slate.",
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ma-storm-graph-read",
    title: "Read the storm graphs",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.DP.1.2"],
    chapterId: "u2-ch5",
    unitId: "u2-camp",
    prompt:
      "A scaled bar graph shows gust counts. A table shows rain marks. Solve one- and two-step problems. The circle graph only shows totals in each category.",
    scaffoldHints: [
      "Read the scale: each bar unit might mean 2 gusts.",
      "'How many more' is a subtract.",
      "A two-step problem might add two days, then compare.",
    ],
    answerRubric: "Correct interpretation of given displays; one- and two-step answers match the data.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Scale: 1 square = 2 gusts. Day 2's bar is 5 squares high. How many gusts?",
        choices: ["5", "7", "10", "25"],
        correctIndex: 2,
      },
      {
        itemType: "multiple_choice",
        prompt: "Day 1: 8 marks. Day 3: 13 marks. How many more on Day 3?",
        choices: ["5", "8", "13", "21"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "Day 1 has 6, Day 2 has 9, Day 4 has 4. What is Day 1 + Day 2, and how many more is that than Day 4?",
        sampleAnswer: "15; 11 more than Day 4.",
      },
    ],
  }),
  a({
    slug: "g3-ma-choose-measure-tools",
    title: "Choose tools at the spring",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.M.1.1"],
    chapterId: "u2-ch6",
    unitId: "u2-camp",
    prompt:
      "Sort jobs: measure a plank to the nearest centimeter or half inch; measure pot water to the nearest milliliter or half cup; measure temperature to the nearest degree. Drag the ruler, beaker, or thermometer.",
    scaffoldHints: [
      "Length uses a ruler or tape.",
      "Liquid in a pot uses a beaker or measuring cup.",
      "Hot/cold air or water uses a thermometer.",
    ],
    answerRubric: "Correct tool for each attribute; mentions appropriate precision from the standard.",
    storySkinNotes: skin + " Location: spring pool.",
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-ma-measure-word-problems",
    title: "Spring and kettle word problems",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.M.1.2"],
    chapterId: "u2-ch6",
    unitId: "u2-camp",
    prompt:
      "Solve real measurement problems with whole numbers. Include units. Do not convert between units.",
    scaffoldHints: [
      "Keep the unit in the answer (cm, cups, °F).",
      "Same units can be added or subtracted.",
      "Multiplication factors stay within 12.",
    ],
    answerRubric: "Correct operations and named units; no conversion required.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Rope is 9 feet. Vey cuts off 4 feet. How much remains?",
        choices: ["5 feet", "13 feet", "36 feet", "5 inches"],
        correctIndex: 0,
      },
      {
        itemType: "multiple_choice",
        prompt: "4 pots hold 6 cups each. How many cups in all?",
        choices: ["10 cups", "18 cups", "24 cups", "64 cups"],
        correctIndex: 2,
      },
      {
        itemType: "free_response",
        prompt: "Morning air is 64°F. It rises 9 degrees, then falls 4 degrees. What is the temperature now? Include °F.",
        sampleAnswer: "69°F",
      },
    ],
  }),
  a({
    slug: "g3-ma-trail-lines",
    title: "Name the trail lines",
    kind: "MAP_EXPLORE",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.GR.1.1"],
    chapterId: "u3-ch7",
    unitId: "u3-map",
    prompt:
      "On the trail map, find and draw points, lines, line segments, rays, intersecting lines, perpendicular lines (square corners), and parallel lines. Label each.",
    scaffoldHints: [
      "A ray has one endpoint and goes on forever one way.",
      "Perpendicular lines meet at a square corner.",
      "Parallel lines never meet.",
    ],
    answerRubric: "Correct identification/drawing of each listed object in 2-D figures.",
    storySkinNotes: skin + " Location: ridge trail.",
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ma-camp-quadrilaterals",
    title: "Sort the camp plots",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.GR.1.2"],
    chapterId: "u3-ch7",
    unitId: "u3-map",
    prompt:
      "Sort plots into parallelograms, rhombi, rectangles, squares, and trapezoids using defining attributes. Include a non-example that is not a quadrilateral.",
    scaffoldHints: [
      "A square is a special rectangle and a special rhombus.",
      "A trapezoid has exactly one pair of parallel sides (use the figure's given definition in-game).",
      "Count sides: four closed sides to be a quadrilateral.",
    ],
    answerRubric: "Correct classification by defining attributes; reasonable drawings if asked.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ma-flag-symmetry",
    title: "Fold the camp flag",
    kind: "CREATIVE_PROJECT",
    prismaKind: "CHALLENGE",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.GR.1.3"],
    chapterId: "u3-ch7",
    unitId: "u3-map",
    prompt:
      "Draw the camp flag. Draw every line of symmetry, or write 'none.' Fold in your mind: both halves must match.",
    scaffoldHints: [
      "A rectangle that is not a square has two lines of symmetry.",
      "Some shapes have one line; some have more; some have zero.",
      "Matching halves means they lie on top of each other.",
    ],
    answerRubric: "Correct number and placement of lines of symmetry for the given figure.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ma-sighting-pattern",
    title: "Extend Idi's sighting pattern",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.AR.3.3"],
    chapterId: "u3-ch8",
    unitId: "u3-map",
    prompt:
      "Idi's bird counts: 3, 6, 9, 12, … Identify the rule, name terms with ordinal words (1st, 2nd, 3rd), extend three more terms, and create a different pattern for crab counts.",
    scaffoldHints: [
      "This rule adds 3 each time (or multiply the position by 3).",
      "The 1st term is 3.",
      "Your new pattern may add, subtract, multiply, or divide whole numbers.",
    ],
    answerRubric: "Rule identified; pattern extended; new pattern created; ordinal language used.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ma-tower-area-formula",
    title: "Tower deck area by formula",
    kind: "CALCULATOR",
    prismaKind: "CHALLENGE",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.GR.2.2"],
    chapterId: "u3-ch9",
    unitId: "u3-map",
    prompt:
      "The deck is a rectangle with whole-number sides (not more than 12 by 12). Find area by counting unit squares AND by multiplying length × width. Write square units in words.",
    scaffoldHints: [
      "Area = length × width for a rectangle.",
      "Counting the array should match the product.",
      "Write 'square meters' or 'square paces,' not a bare number.",
    ],
    answerRubric: "Matching count and formula; sides ≤ 12; units in word form.",
    storySkinNotes: skin + " Calculator is Vey's folding rule.",
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ma-hut-peri-area",
    title: "Hut perimeter and area",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.GR.2.3"],
    chapterId: "u3-ch9",
    unitId: "u3-map",
    prompt:
      "Find perimeter and area of rectangles. Do not find missing side lengths. Sides ≤ 12. Include units in words.",
    scaffoldHints: [
      "Perimeter is the distance around: add all four sides, or 2×length + 2×width.",
      "Area is length × width.",
      "Perimeter units are length units; area units are square units.",
    ],
    answerRubric: "Correct perimeter and area with units; no unknown-side items.",
    storySkinNotes: skin,
    estimatedMinutes: 9,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "A 6-by-4 hut. Area?",
        choices: ["10 square units", "20 square units", "24 square units", "48 square units"],
        correctIndex: 2,
      },
      {
        itemType: "multiple_choice",
        prompt: "Same 6-by-4 hut. Perimeter?",
        choices: ["10 units", "20 units", "24 units", "24 square units"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "A 10-by-3 deck. Find perimeter and area. Use word-form units.",
        sampleAnswer: "Perimeter 26 units; area 30 square units.",
      },
    ],
  }),
  a({
    slug: "g3-ma-l-dock-composite",
    title: "L-shaped landing of two rectangles",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.GR.2.4"],
    chapterId: "u3-ch9",
    unitId: "u3-map",
    prompt:
      "The landing is two non-overlapping rectangles: 8 by 5 and 4 by 3. Find the total area. Then find the perimeter of the composite shape using the given diagram (no hidden sides to invent). Each rectangle ≤ 12 by 12.",
    scaffoldHints: [
      "Add the two areas because they do not overlap.",
      "For perimeter, walk the outside edge only — do not add the inside shared edge twice.",
      "Write square units for area.",
    ],
    answerRubric: "Area = 40 + 12 = 52 square units; perimeter matches the provided outline.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ma-distributive-planks",
    title: "Distributive planks for the hall",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.AR.1.1"],
    chapterId: "u4-ch10",
    unitId: "u4-charter",
    prompt:
      "Vey needs 6 × 14 planks. Show 6 × (10 + 4) with parentheses. Also show a commutative or associative example with one-digit factors (for example 3 × 4 × 2). Name the properties.",
    scaffoldHints: [
      "Distributive: multiply 6×10 and 6×4, then add.",
      "Commutative: 4 × 3 = 3 × 4.",
      "Associative: (2 × 3) × 4 = 2 × (3 × 4).",
    ],
    answerRubric:
      "Correct distributive expansion with parentheses; at least one other named property with one-digit factors; products of three numbers use factors ≤ 12.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ma-unit-fraction-loaf",
    title: "One equal part of the loaf",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.FR.1.1"],
    chapterId: "u4-ch11",
    unitId: "u4-charter",
    prompt:
      "Pell cuts a loaf into n equal parts (n is 2, 3, 4, 5, 6, 8, 10, or 12). Show 1/n as one part of the whole, as part of a set of biscuits, and as a point on a number line.",
    scaffoldHints: [
      "Equal parts must be the same size.",
      "1/8 is smaller than 1/4 because the whole is cut into more pieces.",
      "On a number line from 0 to 1, 1/4 is the first of four equal jumps.",
    ],
    answerRubric: "Correct unit-fraction representations; allowed denominators only.",
    storySkinNotes: skin + " Location: cook fire.",
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ma-m-copies-of-unit",
    title: "Shares as copies of a unit fraction",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.FR.1.2"],
    chapterId: "u4-ch11",
    unitId: "u4-charter",
    prompt:
      "A share m/n means adding 1/n to itself m times — even if the share is greater than one whole (like 5/4 of a water ration).",
    scaffoldHints: [
      "3/4 = 1/4 + 1/4 + 1/4.",
      "5/4 is one whole and one more fourth.",
      "Denominators only 2, 3, 4, 5, 6, 8, 10, 12.",
    ],
    answerRubric: "Interprets m/n as m copies of 1/n; includes at least one fraction > 1.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Which matches 3/5?",
        choices: ["1/3 + 1/5", "1/5 + 1/5 + 1/5", "3 + 5", "1/3 + 1/3 + 1/3 + 1/3 + 1/3"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "5/4 of a loaf is how many fourths?",
        choices: ["1", "4", "5", "9"],
        correctIndex: 2,
      },
      {
        itemType: "free_response",
        prompt: "Write 7/6 as a sum of unit fractions. Is it greater than one whole? Explain.",
        sampleAnswer: "1/6 added 7 times; yes, because 7 > 6.",
      },
    ],
  }),
  a({
    slug: "g3-ma-fraction-names",
    title: "Name the shares three ways",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.FR.1.3"],
    chapterId: "u4-ch11",
    unitId: "u4-charter",
    prompt:
      "After you read Pell's share log, write each bold fraction in standard form, numeral-word form, and word form. Then decide: do we post the standard form or the word form on the cook tent so younger scouts can read it?",
    scaffoldHints: [
      "Standard form looks like 3/8.",
      "Numeral-word form might look like 3 eighths.",
      "Word form: three-eighths.",
    ],
    answerRubric: "Correct three forms for fractions including one > 1; allowed denominators; a justified posting decision.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
    readingText:
      "Cook Pell's share log, copied in a hurry: We split the morning loaf into eight equal parts. Rho took 1/8. Captain, you are owed 3/8 because you skipped last night's biscuit. Mara asked for 5/4 of a water cup — that is more than one full cup, and she will pay it back at supper. Idi wrote 'three-fourths' in words on a scrap, then crossed it out and wrote 3/4. The Guild likes numbers that another ship can read without guessing our handwriting. Decision for the captain: post the cook-tent list in the form the crew will not misread in rain.",
  }),
  a({
    slug: "g3-ma-compare-fraction-shares",
    title: "Compare camp shares",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.FR.2.1"],
    chapterId: "u4-ch11",
    unitId: "u4-charter",
    prompt:
      "Plot, order, and compare fractions that share a numerator or share a denominator. You may use mixed numbers. Denominators 2, 3, 4, 5, 6, 8, 10, 12.",
    scaffoldHints: [
      "Same denominator: the larger numerator is more pieces of the same size.",
      "Same numerator: the larger denominator means smaller pieces.",
      "A number line (like a rope marked in eighths) helps.",
    ],
    answerRubric: "Correct comparisons/order; same numerator or same denominator as required.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Which is greater: 3/8 or 5/8?",
        choices: ["3/8", "5/8", "They are equal", "Cannot tell"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "Which is greater: 1/4 or 1/10?",
        choices: ["1/4", "1/10", "They are equal", "1/10 because 10 is bigger"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "Order 2/5, 4/5, and 1/5 from least to greatest. Explain using same denominators.",
        sampleAnswer: "1/5, 2/5, 4/5; more fifths means more of the whole.",
      },
    ],
  }),
  a({
    slug: "g3-ma-equivalent-ration-bars",
    title: "Same share, different cuts",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.FR.2.2"],
    chapterId: "u4-ch11",
    unitId: "u4-charter",
    prompt:
      "Using the given bars and number lines (already scaled), identify which fractions are equivalent and explain why. You are not asked to invent a new equivalent fraction without a model.",
    scaffoldHints: [
      "Equivalent fractions cover the same amount of the whole.",
      "1/2 and 2/4 line up on the given number line.",
      "If the shaded parts match, the fractions are equivalent.",
    ],
    answerRubric: "Correct identification of equivalents from models; explanation refers to equal amounts.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ma-missing-factor-watch",
    title: "Division as a missing factor",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.AR.2.1"],
    chapterId: "u4-ch12",
    unitId: "u4-charter",
    prompt:
      "Rewrite each division as a missing-factor multiplication. Use a letter or a box for the unknown. Factors within 12.",
    scaffoldHints: [
      "24 ÷ 6 = 4 is the same as 6 × 4 = 24.",
      "The missing factor is the unknown group size or number of groups.",
      "You may write 6 × n = 24.",
    ],
    answerRubric: "Correct restatement as missing-factor equations.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Which matches 18 ÷ 3 = 6?",
        choices: ["3 × 6 = 18", "18 × 3 = 6", "3 + 6 = 18", "18 − 3 = 6"],
        correctIndex: 0,
      },
      {
        itemType: "multiple_choice",
        prompt: "32 ÷ 8 = n is the same as —",
        choices: ["8 × n = 32", "8 + n = 32", "n ÷ 8 = 32", "32 × 8 = n"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "Rewrite 45 ÷ 9 = 5 as a missing-factor problem. Then rewrite 7 × □ = 56 as a division.",
        sampleAnswer: "9 × 5 = 45 or 9 × n = 45; 56 ÷ 7 = 8.",
      },
    ],
  }),
  a({
    slug: "g3-ma-true-false-equations",
    title: "True or false muster equations",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.AR.2.2"],
    chapterId: "u4-ch12",
    unitId: "u4-charter",
    prompt:
      "The equal sign means 'the same amount,' even if the product is on the left. Decide true or false. Three or four terms. Factors within 12.",
    scaffoldHints: [
      "Compute each side.",
      "4 × 6 = 3 × 8 is true because both are 24.",
      "The product can be on either side.",
    ],
    answerRubric: "Correct true/false with a reason that uses the meaning of equality.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Is 5 × 7 = 35 true?",
        choices: ["True", "False"],
        correctIndex: 0,
      },
      {
        itemType: "multiple_choice",
        prompt: "Is 4 × 8 = 6 × 5 true?",
        choices: ["True", "False"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "Is 36 = 9 × 4 true or false? Is 2 × 6 = 3 × 4 true or false? Explain the second one.",
        sampleAnswer: "True; true, because both sides equal 12.",
      },
    ],
  }),
  a({
    slug: "g3-ma-unknown-any-position",
    title: "Unknowns on either side",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.AR.2.3"],
    chapterId: "u4-ch12",
    unitId: "u4-charter",
    prompt:
      "Find the unknown whole number in a multiplication or division equation. The unknown may be any of the three numbers. Factors within 12.",
    scaffoldHints: [
      "Think of the related fact.",
      "If n × 8 = 56, n is 7 because 7 × 8 = 56.",
      "If 48 ÷ n = 6, n is 8.",
    ],
    answerRubric: "Correct unknown in any position.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "n × 9 = 63. n = ?",
        choices: ["6", "7", "8", "54"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "40 ÷ n = 5. n = ?",
        choices: ["8", "9", "35", "45"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "Find n: 6 = n ÷ 7. Show the related multiplication.",
        sampleAnswer: "n = 42 because 6 × 7 = 42.",
      },
    ],
  }),
  a({
    slug: "g3-ma-round-inspector",
    title: "Round for the inspector",
    kind: "CALCULATOR",
    prismaKind: "CHALLENGE",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.NSO.1.4"],
    chapterId: "u5-ch13",
    unitId: "u5-guild",
    prompt:
      "Round whole numbers from 0 to 1,000 to the nearest 10 and nearest 100 for the Guild inspector's columns. Use the calculator to check, but mark the rounding place yourself.",
    scaffoldHints: [
      "Look at the digit to the right of the place you are rounding.",
      "5 or more: round up. 4 or less: stay.",
      "847 to the nearest ten is 850; to the nearest hundred is 800.",
    ],
    answerRubric: "Correct rounding to 10 and 100 within 0–1,000.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-ma-multiples-crates",
    title: "Multiples for crate stacking",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.AR.3.2"],
    chapterId: "u5-ch14",
    unitId: "u5-guild",
    prompt:
      "A number from 1 to 144 is a multiple of a one-digit number if you can make it with that factor. Use multiplication or division to decide.",
    scaffoldHints: [
      "Multiples of 4: 4, 8, 12, 16, …",
      "Divide: if there is no remainder, it is a multiple.",
      "36 ÷ 6 = 6, so 36 is a multiple of 6.",
    ],
    answerRubric: "Correct yes/no with multiplication or division evidence; n ≤ 144; one-digit factor.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Is 42 a multiple of 7?",
        choices: ["Yes", "No"],
        correctIndex: 0,
      },
      {
        itemType: "multiple_choice",
        prompt: "Is 50 a multiple of 8?",
        choices: ["Yes", "No"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "Is 96 a multiple of 6? Show a multiplication or division.",
        sampleAnswer: "Yes; 6 × 16 = 96 or 96 ÷ 6 = 16.",
      },
    ],
  }),
  a({
    slug: "g3-ma-market-two-step",
    title: "Market board two-step (enterprise)",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "math_g3",
    targetStandardCodes: ["MA.3.AR.1.2"],
    chapterId: "u6-ch17",
    unitId: "u6-enterprise",
    prompt:
      "Market Day hides two-step stories. This is a second activity so MA.3.AR.1.2 is not only bundled with the camp budget. Factors within 12.",
    scaffoldHints: [
      "Find the hidden first question.",
      "Keep track of coins or goods.",
      "Write a number sentence for each step.",
    ],
    answerRubric: "Correct two-step solutions with operations matching the story.",
    storySkinNotes: skin + " Location: river-edge market.",
    estimatedMinutes: 10,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Nails cost 3 coins each. You buy 8, then spend 6 more coins on twine. Total coins?",
        choices: ["17", "24", "30", "11"],
        correctIndex: 2,
      },
      {
        itemType: "multiple_choice",
        prompt: "12 fish in a basket shared equally by 4 scouts. Then Pell gives one scout 2 extra fish. How many does that scout have?",
        choices: ["3", "5", "6", "8"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "A coil is 9 coins. You buy 5 coils, pay with 50 coins. How much change? Show two steps.",
        sampleAnswer: "9×5=45; 50−45=5 coins change.",
      },
    ],
  }),
];
