import type { ActivityTemplate } from "../prisma/seeds/activities/types";

function a(partial: Omit<ActivityTemplate, "authoring">): ActivityTemplate {
  return { authoring: "HAND_AUTHORED", ...partial };
}

const camp =
  "Bind displayName as Captain. Rho is First Mate. Camp civics may practice fairness; they do not replace U.S. or Florida facts.";
const atlas =
  "Setting: wreck library / Guild atlas / sealed civics folio. These are Earth sources. Do not rename Florida as a cove or the Constitution as a camp charter.";

export const ssActivities: ActivityTemplate[] = [
  a({
    slug: "g3-ss-primary-secondary-wreck",
    title: "Primary or secondary wreck paper?",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.A.1.1"],
    chapterId: "u1-ch1",
    unitId: "u1-crash",
    prompt:
      "Analyze primary and secondary sources. Sort: stained sailing log written during the wreck (primary); Rho retelling the wreck at the fire (secondary); a sketch Idi made while standing on the beach (primary).",
    scaffoldHints: [
      "Primary: made at the time by someone there.",
      "Secondary: tells about it later.",
      "A copy of a primary source is still based on a primary source — say so if unsure.",
    ],
    answerRubric: "Correct primary vs secondary with a reason.",
    storySkinNotes: camp,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-ss-social-science-terms",
    title: "Name the social-science jobs",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.A.1.3"],
    chapterId: "u1-ch1",
    unitId: "u1-crash",
    prompt:
      "Define terms related to the social sciences: history, geography, economics, civics, government. Match each to a first-night task.",
    scaffoldHints: [
      "History: what happened.",
      "Geography: place and land.",
      "Economics: goods, scarcity, trade.",
      "Civics/government: rules and who decides.",
    ],
    answerRubric: "Correct definitions/matches for the social-science terms.",
    storySkinNotes: camp,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Counting biscuit tins because there are not enough is closest to —",
        choices: ["geography", "economics", "a haiku", "astronomy"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "Drawing where the reef is sits in —",
        choices: ["geography", "only math", "cooking", "figurative language"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "In one sentence each, define history and civics using camp work.",
        sampleAnswer: "History: recording what happened in the wreck. Civics: making fair first-night rules.",
      },
    ],
  }),
  a({
    slug: "g3-ss-scarcity-trade",
    title: "Scarcity on the ration tarp",
    kind: "STORY_SCENE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.E.1.1"],
    chapterId: "u1-ch2",
    unitId: "u1-crash",
    prompt:
      "Give examples of how scarcity results in trade. There is not enough rope. What might the crew trade to get more without taking someone's share by force?",
    scaffoldHints: [
      "Scarcity means not enough of something.",
      "Trade is giving one thing to get another.",
      "Fairness still matters.",
    ],
    answerRubric: "Clear scarcity → trade example.",
    storySkinNotes: camp,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-ss-civic-virtue-camp",
    title: "Civility when shares are short",
    kind: "CREW_DIALOGUE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.CG.2.1"],
    chapterId: "u1-ch2",
    unitId: "u1-crash",
    prompt:
      "Describe how citizens demonstrate civility, cooperation, volunteerism, and other civic virtues. Map folio examples (food drives, clean-ups) onto honest camp actions: extra watch, sharing, cleaning the spring. Do not pretend a camp vote is a U.S. election.",
    scaffoldHints: [
      "Civility is manners under pressure.",
      "Volunteerism is helping without being forced.",
      "Name one Earth example from the clarification list if you know it, plus one camp parallel.",
    ],
    answerRubric: "Describes civic virtues with real examples; camp parallel does not replace citizenship content.",
    storySkinNotes: camp,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ss-thematic-search-map",
    title: "Read the search-party thematic map",
    kind: "MAP_EXPLORE",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.1.1"],
    chapterId: "u1-ch3",
    unitId: "u1-crash",
    prompt:
      "Use thematic maps, tables, charts, graphs, and photos to analyze geographic information. The search map colors show 'searched / unsearched / wet ground.' A table lists water sightings. State two geographic facts.",
    scaffoldHints: [
      "A thematic map shows one kind of information.",
      "Read the key first.",
      "A photo of the ridge is geographic information too.",
    ],
    answerRubric: "Pulls accurate geographic information from more than one display type.",
    storySkinNotes: camp,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ss-map-elements",
    title: "Finish the map frame",
    kind: "MAP_EXPLORE",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.1.2"],
    chapterId: "u1-ch3",
    unitId: "u1-crash",
    prompt:
      "Review basic map elements: coordinate grid, cardinal and intermediate directions, title, compass rose, scale, key/legend with symbols. Add any missing piece to the search sketch.",
    scaffoldHints: [
      "Cardinal: N S E W. Intermediate: NE, SW, …",
      "The key explains symbols.",
      "Scale tells distance.",
    ],
    answerRubric: "Identifies/adds the listed map elements correctly.",
    storySkinNotes: camp,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ss-map-scale-distance",
    title: "Scale between two marks",
    kind: "CALCULATOR",
    prismaKind: "CHALLENGE",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.1.6"],
    chapterId: "u1-ch3",
    unitId: "u1-crash",
    prompt:
      "Use maps to identify different types of scale to measure distances between two places. Measure camp-to-split-rock using the bar scale (and note if a verbal scale is also printed).",
    scaffoldHints: [
      "A bar scale is a line that stands for real distance.",
      "A verbal scale might say '1 inch = 100 paces.'",
      "Measure on the map, then use the scale — do not guess paces from memory.",
    ],
    answerRubric: "Uses scale (not a wild guess) to state distance between two places.",
    storySkinNotes: camp,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ss-tech-gather-source",
    title: "Tem's reader gathers a source",
    kind: "CREW_DIALOGUE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.A.1.2"],
    chapterId: "u2-ch4",
    unitId: "u2-camp",
    prompt:
      "Utilize technology resources to gather information from primary and secondary sources. Use Signaler Tem's recovered reader to open one wreck file and one later summary. Name which is which and one fact you gathered.",
    scaffoldHints: [
      "The tool is the reader (technology).",
      "You still have to tell primary from secondary.",
      "Write the fact in your own words.",
    ],
    answerRubric: "Uses a tech resource; gathers from primary and/or secondary; names the source type.",
    storySkinNotes: camp,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ss-buyer-seller",
    title: "Buyer and seller at the river",
    kind: "STORY_SCENE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.E.1.3"],
    chapterId: "u2-ch4",
    unitId: "u2-camp",
    prompt:
      "Recognize that buyers and sellers interact to exchange goods and services through trade or money. Diagram today's deal: who buys, who sells, what good or service moves.",
    scaffoldHints: [
      "A service is work, not a thing (repairing a pot).",
      "Money or barter both count as exchange.",
      "Both sides should be named.",
    ],
    answerRubric: "Correctly identifies buyer, seller, and exchange type.",
    storySkinNotes: camp,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-ss-map-types",
    title: "Four map types, four jobs",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.1.4"],
    chapterId: "u2-ch5",
    unitId: "u2-camp",
    prompt:
      "Name and identify the purpose of maps: physical, political, elevation, population. Use island physical/elevation sketches plus Guild-atlas political and population plates (Earth). Match each type to a question it answers.",
    scaffoldHints: [
      "Physical: landforms, water.",
      "Political: countries, borders, cities.",
      "Elevation: height of land.",
      "Population: how many people where.",
    ],
    answerRubric: "Correct purpose for all four named map types.",
    storySkinNotes: camp + " " + atlas,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ss-maps-vs-globes",
    title: "Atlas page vs wreck globe",
    kind: "STORY_SCENE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.1.5"],
    chapterId: "u3-ch7",
    unitId: "u3-map",
    prompt:
      "Compare maps and globes to understand distortion. Look at Greenland or another high-latitude land on the paper Guild world map vs the globe. Explain one way the flat map stretches or shrinks a place.",
    scaffoldHints: [
      "A globe is round like Earth.",
      "A flat map has to squash a round world.",
      "Distortion means the shape or size is not perfectly true.",
    ],
    answerRubric: "Compares map vs globe; explains distortion with a concrete example.",
    storySkinNotes: atlas,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ss-perceive-the-cove",
    title: "Two mental maps of one cove",
    kind: "CREW_DIALOGUE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.2.6"],
    chapterId: "u3-ch8",
    unitId: "u3-map",
    prompt:
      "Investigate how people perceive places differently by conducting interviews, mental mapping, and studying a song or legend about the cove. Interview Pell and Mara; draw two mental maps.",
    scaffoldHints: [
      "Perception is how someone thinks and feels about a place.",
      "A mental map is the picture in their head, not the measured map.",
      "A song can make a ridge feel safe or haunted without changing the rocks.",
    ],
    answerRubric: "Shows different perceptions via interview/mental map/song; same place.",
    storySkinNotes: camp,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ss-tower-scale-again",
    title: "Tower-to-camp on the scaled map",
    kind: "MAP_EXPLORE",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.1.6"],
    chapterId: "u3-ch9",
    unitId: "u3-map",
    prompt:
      "Second scale task so G.1.6 is not only bundled with Chapter 3. Measure tower-to-camp with the map scale. Name the type of scale you used.",
    scaffoldHints: [
      "Use the key's scale, not your footsteps in the sand.",
      "Say whether it is a bar scale or a verbal scale.",
      "Units should match the key.",
    ],
    answerRubric: "Distance from scale; scale type named. Dedicated extra practice.",
    storySkinNotes: camp,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-ss-continents-oceans",
    title: "Label continents and oceans",
    kind: "MAP_EXPLORE",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.1.3"],
    chapterId: "u5-ch13",
    unitId: "u5-guild",
    prompt:
      "Label the continents and oceans on a world map from the Guild atlas (Earth). This is not a map of the crash island.",
    scaffoldHints: [
      "Seven continents, five oceans is the usual school set.",
      "The Pacific is the largest ocean.",
      "Antarctica is a continent.",
    ],
    answerRubric: "Correct labels on a world map; Earth geography.",
    storySkinNotes: atlas,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ss-north-america-caribbean",
    title: "Label North America and the Caribbean",
    kind: "MAP_EXPLORE",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.2.1"],
    chapterId: "u5-ch14",
    unitId: "u5-guild",
    prompt:
      "Label Canada, the United States, Mexico, and in the Caribbean: Puerto Rico, Cuba, Bahamas, Dominican Republic, Haiti, Jamaica — from the atlas plate.",
    scaffoldHints: [
      "Mexico is south of the United States.",
      "Canada is north.",
      "The Caribbean islands are in the sea to the southeast of the U.S. mainland.",
    ],
    answerRubric: "Correct labels for the listed countries/commonwealths.",
    storySkinNotes: atlas,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ss-us-five-regions",
    title: "Five regions of the United States",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.2.2"],
    chapterId: "u5-ch14",
    unitId: "u5-guild",
    prompt:
      "Identify the five regions of the United States on the atlas plate (use the plate's regional names). Do not invent island regions.",
    scaffoldHints: [
      "School maps often use Northeast, Southeast, Midwest, Southwest, West — follow the atlas key.",
      "Florida is in the Southeast on typical U.S. region maps.",
      "Regions are groups of states, not camp neighborhoods.",
    ],
    answerRubric: "Correct identification of the five U.S. regions per the given map.",
    storySkinNotes: atlas,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ss-states-in-regions",
    title: "Place states in U.S. regions",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.2.3"],
    chapterId: "u5-ch14",
    unitId: "u5-guild",
    prompt:
      "Label the states in each of the five regions using the atlas. You will not memorize all 50 in one sitting — complete the plate's required set.",
    scaffoldHints: [
      "Match the atlas list, not a guess.",
      "A state belongs to one region on this map.",
      "Florida goes with its region on the plate.",
    ],
    answerRubric: "Correct regional placement for the assigned states.",
    storySkinNotes: atlas,
    estimatedMinutes: 15,
  }),
  a({
    slug: "g3-ss-physical-features-na",
    title: "Physical features: U.S., Canada, Mexico, Caribbean",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.2.4"],
    chapterId: "u5-ch15",
    unitId: "u5-guild",
    prompt:
      "Describe physical features from the atlas. Then decide which two features belong on the Guild 'Earth lands' poster.",
    scaffoldHints: [
      "Physical features: mountains, rivers, plains, islands — not cities.",
      "Use names from the page.",
      "Do not rename them as camp rocks.",
    ],
    answerRubric: "Accurate descriptions from sources; poster choices are physical features.",
    storySkinNotes: atlas,
    estimatedMinutes: 12,
    readingText:
      "Guild atlas, Lands plate (abridged). The United States includes the Rocky Mountains in the west and the Mississippi River in the center. Canada stretches to cold northern lands and includes the Canadian Shield of ancient rock. Mexico has high plateaus and volcanoes near its center. The Caribbean is a chain of islands in a warm sea. These are Earth places in a found book. They are not coves on our crash beach. Rho says: copy the names honestly.",
  }),
  a({
    slug: "g3-ss-landmarks-na",
    title: "Natural and man-made landmarks",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.2.5"],
    chapterId: "u5-ch15",
    unitId: "u5-guild",
    prompt:
      "Identify natural and man-made landmarks in the United States, Canada, Mexico, and the Caribbean from the atlas list (for example a mountain vs a monument).",
    scaffoldHints: [
      "Natural: made by Earth (canyon, waterfall).",
      "Man-made: built by people (statue, canal, large building).",
      "Match the atlas, not camp decorations.",
    ],
    answerRubric: "Correctly distinguishes and identifies landmarks from the source list.",
    storySkinNotes: atlas,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "A mountain in the atlas is a —",
        choices: ["man-made landmark", "natural landmark", "currency", "verb tense"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "A famous monument built by people is —",
        choices: ["a natural landmark", "a man-made landmark", "a fraction", "a star"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "Name one natural and one man-made landmark from the atlas page you studied.",
        sampleAnswer: "Depends on plate; e.g., a named mountain vs a named monument/building.",
      },
    ],
  }),
  a({
    slug: "g3-ss-climate-vegetation",
    title: "Climate and vegetation plates",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.3.1"],
    chapterId: "u5-ch15",
    unitId: "u5-guild",
    prompt:
      "Describe the climate and vegetation in the United States, Canada, Mexico, and the Caribbean using atlas notes. Compare at least two of those places.",
    scaffoldHints: [
      "Climate is the usual weather of a place over a long time.",
      "Vegetation is the plant life.",
      "Canada's north is not the same as the Caribbean.",
    ],
    answerRubric: "Accurate source-based climate/vegetation descriptions and a comparison.",
    storySkinNotes: atlas,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ss-natural-resources",
    title: "Natural resources in the atlas",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.3.2"],
    chapterId: "u5-ch15",
    unitId: "u5-guild",
    prompt:
      "Describe natural resources in the United States, Canada, Mexico, and the Caribbean as listed (forests, minerals, fish, farmland, etc.).",
    scaffoldHints: [
      "A natural resource comes from nature and people use it.",
      "Follow the atlas icons.",
      "Camp timber is not a U.S. resource answer.",
    ],
    answerRubric: "Names major resources from the four named places using the source.",
    storySkinNotes: atlas,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "A natural resource is closest to —",
        choices: ["a made-up camp coin", "something from nature people use", "a poem", "a verb"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "Which source should you use for this standard?",
        choices: ["Only the island garden", "The Guild atlas resource plate", "A limerick", "The cook's mood"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "Name one natural resource each for two of: U.S., Canada, Mexico, Caribbean — from the plate.",
        sampleAnswer: "Plate-dependent; must match atlas.",
      },
    ],
  }),
  a({
    slug: "g3-ss-environment-settlement",
    title: "How environment shapes settlement (Earth)",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.4.1"],
    chapterId: "u5-ch15",
    unitId: "u5-guild",
    prompt:
      "Explain how the environment influences settlement patterns in the United States, Canada, Mexico, and the Caribbean. Use atlas examples (rivers, coasts, harsh climate). You may add one sentence of transfer ('our camp also sits by fresh water') only after the Earth explanation.",
    scaffoldHints: [
      "People often settle where there is water, food, or milder climate.",
      "Mountains and deserts can limit towns.",
      "The standard is about those Earth places first.",
    ],
    answerRubric: "Earth-based explanation of environment → settlement; optional transfer does not replace it.",
    storySkinNotes: atlas,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ss-cultures-settled",
    title: "Cultures that settled these lands",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.4.2"],
    chapterId: "u5-ch15",
    unitId: "u5-guild",
    prompt:
      "Identify cultures that have settled the United States, Canada, Mexico, and the Caribbean from the atlas peoples plate. Then decide which two names to copy onto the library poster — they must be from the plate.",
    scaffoldHints: [
      "Culture includes language, traditions, and ways of life.",
      "Indigenous peoples and later settlers both appear in honest textbooks — follow the plate.",
      "Do not invent a 'Cove People' as a substitute.",
    ],
    answerRubric: "Identifies cultures from the source for the named places.",
    storySkinNotes: atlas,
    estimatedMinutes: 12,
    readingText:
      "Guild atlas, Peoples plate (school short). Many Native nations lived in North America long before later arrivals. The United States and Canada also include people whose families came from Europe, Africa, Asia, and other places. Mexico's cultures include Indigenous peoples and Spanish colonial history. The Caribbean includes Indigenous Taíno heritage and later African, European, and other communities. This plate is Earth history. Copy names as printed. Do not replace them with camp nicknames.",
  }),
  a({
    slug: "g3-ss-compare-cultures",
    title: "Compare a U.S. region with a neighbor",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.4.3"],
    chapterId: "u5-ch15",
    unitId: "u5-guild",
    prompt:
      "Compare cultural characteristics of diverse populations in one of the five U.S. regions with Canada, Mexico, or the Caribbean. Use two atlas notes (food, language, celebration, or housing as given).",
    scaffoldHints: [
      "Pick one U.S. region.",
      "Pick Canada or Mexico or the Caribbean.",
      "Compare: alike and different, from the text.",
    ],
    answerRubric: "Valid comparison of cultural characteristics using sources.",
    storySkinNotes: atlas,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ss-ethnic-contributions",
    title: "Contributions to the United States",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.G.4.4"],
    chapterId: "u5-ch15",
    unitId: "u5-guild",
    prompt:
      "Identify contributions from various ethnic groups to the United States using the atlas examples (food, music, inventions, holidays, words — as printed).",
    scaffoldHints: [
      "A contribution is something added that others use or remember.",
      "Use named groups from the page.",
      "Do not invent a camp 'ethnic group.'",
    ],
    answerRubric: "Identifies a real contribution tied to an ethnic group from the source.",
    storySkinNotes: atlas,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "This standard is about contributions to —",
        choices: ["only our crash camp", "the United States", "the signal tower", "fractions"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "A contribution might be —",
        choices: ["a food, art, idea, or holiday others share", "hiding the atlas", "skipping the folio", "a made-up cove law"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "Name one ethnic group from the plate and one contribution listed.",
        sampleAnswer: "Must match the atlas plate used in-session.",
      },
    ],
  }),
  a({
    slug: "g3-ss-constitution-purpose",
    title: "Why the U.S. Constitution exists",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.CG.1.1"],
    chapterId: "u5-ch16",
    unitId: "u5-guild",
    prompt:
      "Explain how the U.S. Constitution establishes the purpose and fulfills the need for government (rights, organization, security, services). Camp rules may be a comparison only after the Earth explanation.",
    scaffoldHints: [
      "Purpose of government: protect rights, organize, security, services.",
      "The Constitution is a real U.S. document.",
      "A camp charter is not the Constitution.",
    ],
    answerRubric: "Explains U.S. Constitution purpose/need; does not substitute camp law.",
    storySkinNotes: atlas,
    estimatedMinutes: 12,
    readingText:
      "Sealed civics folio. The U.S. Constitution is the plan for the national government of the United States. It exists because people need government for protection of rights, organization, security, and services. It is not a pirate code and it is not our beach charter. If we compare, we say: our camp also needs fair rules — but that comparison does not rewrite 1787. Rho will stop you if you call the captain 'President of Florida.'",
  }),
  a({
    slug: "g3-ss-consent-of-governed",
    title: "We the People",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.CG.1.2"],
    chapterId: "u5-ch16",
    unitId: "u5-guild",
    prompt:
      "Describe how the U.S. government gains its power from the people: 'We the People,' consent of the governed, voting and elections, a republic with representatives.",
    scaffoldHints: [
      "Consent means agreement.",
      "People vote for representatives.",
      "A camp show of hands is practice in civility, not a U.S. election.",
    ],
    answerRubric: "Correct U.S. civic ideas; no substitution of camp vote for the standard.",
    storySkinNotes: atlas,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "'We the People' means government power comes from —",
        choices: ["the captain only", "the people", "the signal lamp", "a trader"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "Consent of the governed is shown in the U.S. by —",
        choices: ["voting and elections", "shouting the loudest", "hiding the folio", "skipping holidays"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "What is a republic, in the folio's sense, in one or two sentences?",
        sampleAnswer: "A government where the people choose representatives to make decisions.",
      },
    ],
  }),
  a({
    slug: "g3-ss-voting-elections",
    title: "Why voting matters (folio)",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.CG.2.2"],
    chapterId: "u5-ch16",
    unitId: "u5-guild",
    prompt:
      "Describe the importance of voting in elections. It is a citizen's responsibility in a republic. Do not replace this with 'whoever the captain likes.'",
    scaffoldHints: [
      "Voting chooses representatives.",
      "If people do not vote, fewer voices are heard.",
      "Cite the folio.",
    ],
    answerRubric: "Explains voting in a republic as civic responsibility.",
    storySkinNotes: atlas,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ss-patriotic-holidays",
    title: "Patriotic holidays and observances",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.CG.2.3"],
    chapterId: "u5-ch16",
    unitId: "u5-guild",
    prompt:
      "Explain the history and meaning behind patriotic holidays (American Founders Month, Celebrate Freedom Week, Constitution Day, Independence Day, Martin Luther King Jr. Day, Medal of Honor Day, Memorial Day, Patriot Day, Veterans Day — as listed). Match each card to its meaning.",
    scaffoldHints: [
      "Independence Day remembers July 4 and independence.",
      "Veterans Day honors people who served in the military.",
      "Memorial Day honors those who died in service — off-screen, no gore.",
    ],
    answerRubric: "Correct holiday-to-meaning matches from the Florida list.",
    storySkinNotes: atlas,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-ss-us-symbols",
    title: "Symbols of the United States",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.CG.2.4"],
    chapterId: "u5-ch16",
    unitId: "u5-guild",
    prompt:
      "Recognize symbols, individuals, documents, and events that represent the United States (Mount Rushmore, Uncle Sam, Washington Monument; James Madison, Alexander Hamilton, Booker T. Washington, Susan B. Anthony; the U.S. Constitution; Constitutional Convention and signing, Sept 17, 1787).",
    scaffoldHints: [
      "Match the clarification list.",
      "The Constitution is a document.",
      "1787 is the convention/signing year.",
    ],
    answerRubric: "Correct recognition from the specified U.S. list.",
    storySkinNotes: atlas,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "A document that represents the United States in this standard is —",
        choices: ["the camp charter", "the U.S. Constitution", "Pell's recipe", "a tide chart"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "The Constitutional Convention is remembered in —",
        choices: ["2026 only", "May–September 1787 (signing September 17, 1787)", "the crash week", "Florida statehood day only"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "Name one U.S. symbol and one individual from the folio list.",
        sampleAnswer: "e.g., Washington Monument; Susan B. Anthony (or others on the list).",
      },
    ],
  }),
  a({
    slug: "g3-ss-florida-symbols",
    title: "Symbols of Florida",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.CG.2.5"],
    chapterId: "u5-ch16",
    unitId: "u5-guild",
    prompt:
      "Recognize Florida symbols, individuals, documents, and events: Great Seal; William Pope Duval, William Dunn Moseley, Josiah T. Walls; Declaration of Rights in the Florida Constitution; statehood March 3, 1845 (27th state).",
    scaffoldHints: [
      "Florida is the 27th state, 1845.",
      "The Declaration of Rights is in the Florida Constitution.",
      "This is not the crash island renamed Florida.",
    ],
    answerRubric: "Correct Florida recognition items from the clarification list.",
    storySkinNotes: atlas,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Florida became a U.S. state on —",
        choices: ["September 17, 1787", "March 3, 1845", "July 4, 1776", "the day of the wreck"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "A Florida symbol in this standard is —",
        choices: ["the Great Seal of the State of Florida", "the camp biscuit stamp", "Mount Rushmore", "Uncle Sam only"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "Name the Florida document mentioned (Declaration of Rights) and what larger constitution it is part of.",
        sampleAnswer: "Declaration of Rights in the Florida Constitution.",
      },
    ],
  }),
  a({
    slug: "g3-ss-constitutions-structure",
    title: "Three branches, two constitutions",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.CG.3.1"],
    chapterId: "u5-ch16",
    unitId: "u5-guild",
    prompt:
      "Explain how the U.S. and Florida Constitutions establish structure, function, powers, and limits of government. Include three branches. Give examples of people who make and enforce laws (Congress and president; Florida legislature and governor).",
    scaffoldHints: [
      "Three branches: legislative makes laws, executive carries them out, judicial interprets — at Grade 3 language.",
      "National vs Florida state.",
      "Do not invent a fourth 'captain branch.'",
    ],
    answerRubric: "Accurate Grade 3 explanation of constitutional structure for U.S. and Florida.",
    storySkinNotes: atlas,
    estimatedMinutes: 15,
  }),
  a({
    slug: "g3-ss-three-levels",
    title: "Local, state, national",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.CG.3.2"],
    chapterId: "u5-ch16",
    unitId: "u5-guild",
    prompt:
      "Recognize that government has local, state, and national levels with different responsibilities. Sort services/examples from the folio (city/county, Florida, United States).",
    scaffoldHints: [
      "National: the whole country.",
      "State: Florida.",
      "Local: city or county.",
    ],
    answerRubric: "Correct level-to-responsibility matches.",
    storySkinNotes: atlas,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-ss-aa-heroism",
    title: "African American heroism and patriotism",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.AA.1.1"],
    chapterId: "u5-ch16",
    unitId: "u5-guild",
    prompt:
      "Identify African Americans who demonstrated heroism and patriotism from the named list (Booker T. Washington, Jesse Owens, Tuskegee Airmen, Martin Luther King Jr., Rosa Parks, President Barack Obama, 1st Lt. Vernon Baker, Sgt. 1st Class Melvin Morris). Choose two. Say what the folio says they did. No gore; courage may be civil or military as the source states.",
    scaffoldHints: [
      "Use the names on the list.",
      "Heroism and patriotism are shown by actions in the source.",
      "This is Earth history, not a camp character rename.",
    ],
    answerRubric: "Identifies named figures with accurate source-based actions.",
    storySkinNotes: atlas,
    estimatedMinutes: 12,
    readingText:
      "Honor folio (short). Booker T. Washington worked for education. Jesse Owens showed excellence and courage as an athlete on the world stage. The Tuskegee Airmen served with distinction as military aviators. Martin Luther King Jr. led a movement for civil rights with nonviolent protest. Rosa Parks is remembered for refusing to give up her bus seat as part of that struggle. Barack Obama served as President of the United States. Vernon Baker and Melvin Morris are remembered for military heroism. Copy two names and one fact each. Do not turn them into wreck-crew nicknames.",
  }),
  a({
    slug: "g3-ss-currencies",
    title: "Currencies of North America and the Caribbean",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.E.1.4"],
    chapterId: "u5-ch16",
    unitId: "u5-guild",
    prompt:
      "Distinguish currencies used in the United States, Canada, Mexico, and the Caribbean from the economics plate (U.S. dollar, Canadian dollar, Mexican peso, and named Caribbean currencies as printed).",
    scaffoldHints: [
      "The U.S. uses the dollar.",
      "Mexico uses the peso.",
      "Do not call Guild scrip the Mexican peso.",
    ],
    answerRubric: "Correct currency-to-country matches from the plate.",
    storySkinNotes: atlas,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-ss-money-characteristics",
    title: "What makes money money",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "social_studies_g3",
    targetStandardCodes: ["SS.3.E.1.2"],
    chapterId: "u6-ch17",
    unitId: "u6-enterprise",
    prompt:
      "List the characteristics of money (portable, divisible, accepted, durable, etc. as taught). Compare Guild coins to a too-heavy sack of nails used as 'pay.'",
    scaffoldHints: [
      "If nobody accepts it, it is a poor money.",
      "If you cannot make change, it is hard to use.",
      "Money should not rot in a week.",
    ],
    answerRubric: "Lists real characteristics of money; comparison makes sense.",
    storySkinNotes: camp,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "A good characteristic of money is that it is —",
        choices: ["impossible to carry", "accepted as payment", "a secret only Pell knows", "always a mountain"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "Nails that rust in rain are a poor money mainly because they are not —",
        choices: ["durable", "a continent", "a holiday", "a branch of government"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "List three characteristics of money in your own words.",
        sampleAnswer: "Portable, divisible, accepted, durable (any three taught).",
      },
    ],
  }),
];
