import type { ActivityTemplate } from "../prisma/seeds/activities/types";

function a(partial: Omit<ActivityTemplate, "authoring">): ActivityTemplate {
  return { authoring: "HAND_AUTHORED", ...partial };
}

const skin =
  "Bind displayName as Captain. Do not reveal that the island is on another planet. Sun/stars language follows Earth science from the Guild primer plus local observation.";

export const scienceActivities: ActivityTemplate[] = [
  a({
    slug: "g3-sci-wreck-questions",
    title: "Raise first-night science questions",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.N.1.1"],
    chapterId: "u1-ch1",
    unitId: "u1-crash",
    prompt:
      "Raise questions about the beach and salvage. Investigate with Rho (team) and alone. Write an explanation based on what you actually explore — not a guess from a storybook.",
    scaffoldHints: [
      "A good question can be checked by looking, smelling (no tasting unknown things), or measuring.",
      "Write what you did, not only what you wished.",
      "An explanation must point to the exploration.",
    ],
    answerRubric: "Testable questions; evidence of exploration; explanation tied to observations.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-sci-salvage-records",
    title: "Keep the salvage chart",
    kind: "SPREADSHEET",
    prismaKind: "CHALLENGE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.N.1.3"],
    chapterId: "u1-ch1",
    unitId: "u1-crash",
    prompt:
      "Keep records of the investigation: pictures, words, or a simple chart. Three rows minimum (what you looked at, what you noticed, when).",
    scaffoldHints: [
      "A chart is a record, not a decoration.",
      "Pictorial records count.",
      "Write enough that Tem could repeat the look tomorrow.",
    ],
    answerRubric: "Appropriate records of an investigation (pictorial, written, or chart).",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-sci-sort-properties",
    title: "Sort salvage by properties",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.P.8.3"],
    chapterId: "u1-ch1",
    unitId: "u1-crash",
    prompt:
      "Compare materials by size, shape, color, texture, and hardness. Sort sailcloth, wet wood, dry wood, iron fittings, and smooth stones. Do not taste anything.",
    scaffoldHints: [
      "Hardness: which scratches, which dents.",
      "Texture: rough, smooth, sticky.",
      "Two objects can share color and still differ in hardness.",
    ],
    answerRubric: "Sorts using listed observable properties; comparisons are accurate to the items.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-sci-temperature-stores",
    title: "Compare store temperatures",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.P.8.1"],
    chapterId: "u1-ch2",
    unitId: "u1-crash",
    prompt:
      "Measure and compare temperatures of shade water, sun water, a sun-warmed stone, and a shaded tin. Use the camp thermometers. Record which is colder/hotter.",
    scaffoldHints: [
      "Wait until the thermometer reading settles.",
      "Compare numbers, not just 'feels warm.'",
      "Solids and liquids both get a reading.",
    ],
    answerRubric: "Temperatures compared with measurements, not guesses.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-sci-sun-heats-stores",
    title: "Sun on the biscuit tin",
    kind: "STORY_SCENE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.E.6.1"],
    chapterId: "u1-ch2",
    unitId: "u1-crash",
    prompt:
      "Demonstrate (or explain from a camp demo) that radiant energy from the Sun heats objects, and when the Sun is not present, heat may be lost. Decide: sun tarp or shade barrel for the fat biscuits?",
    scaffoldHints: [
      "Radiant energy is energy that travels from the Sun to the tin.",
      "After sunset, the tin can cool.",
      "Your storage decision must use heating and heat loss, not 'I like shade.'",
    ],
    answerRubric: "Explains sun heating and heat loss; storage decision follows.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-sci-infer-spoilage",
    title: "Infer from the smell log",
    kind: "CREW_DIALOGUE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.N.1.6"],
    chapterId: "u1-ch2",
    unitId: "u1-crash",
    prompt:
      "Pell lists observations: sun tin warmer; sour smell after noon; shade tin cooler; no sour smell. Infer why. An inference is not a wild story — it is based on the observations.",
    scaffoldHints: [
      "Start with 'I infer … because …'",
      "Do not invent germs if you did not observe them; you may infer heat + time.",
      "If two observations conflict, say so.",
    ],
    answerRubric: "Inference clearly based on given observations.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-sci-classify-animals",
    title: "Classify island animal signs",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.L.15.1"],
    chapterId: "u1-ch3",
    unitId: "u1-crash",
    prompt:
      "Classify animals into major groups (mammals, birds, reptiles, amphibians, fish, arthropods; vertebrates/invertebrates; live birth vs eggs) using physical characteristics and behaviors from tracks, feathers, shells, and Idi's notes. No hunting scenes.",
    scaffoldHints: [
      "Feathers → bird. Fur/milk clues → mammal.",
      "Six legs often means arthropod.",
      "Fish live in water and have gills; do not guess a mammal into the reef without traits.",
    ],
    answerRubric: "Correct grouping using traits/behaviors from the evidence cards.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-sci-empirical-search",
    title: "Evidence, not hunches, on the trail",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.N.1.7"],
    chapterId: "u1-ch3",
    unitId: "u1-crash",
    prompt:
      "Explain that empirical evidence is information such as observations or measurements used to validate an explanation. Give one trail explanation that is backed by evidence and one that is not.",
    scaffoldHints: [
      "A broken twig you saw is evidence.",
      "'I just know they went west' is not.",
      "Measurements count (pace counts, time).",
    ],
    answerRubric: "Correct definition; valid vs invalid example from camp.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-sci-mass-volume-trade",
    title: "Mass and volume of trade lots",
    kind: "CALCULATOR",
    prismaKind: "CHALLENGE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.P.8.2"],
    chapterId: "u2-ch4",
    unitId: "u2-camp",
    prompt:
      "Measure and compare mass and volume of two sacks and a jar of water. A bigger-looking sack may not have more mass. Record numbers and units.",
    scaffoldHints: [
      "Mass is measured with a balance; volume of liquid with a beaker.",
      "Do not mix the two words.",
      "Compare: which has more mass? which has more volume?",
    ],
    answerRubric: "Mass and volume both measured and compared.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-sci-compare-group-obs",
    title: "Why did two teams disagree?",
    kind: "CREW_DIALOGUE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.N.1.2"],
    chapterId: "u2-ch4",
    unitId: "u2-camp",
    prompt:
      "Idi and Tem used the same balance on the same sack and got different numbers. Compare the observations and seek reasons (not blame).",
    scaffoldHints: [
      "Did they zero the balance?",
      "Did wind push the pan?",
      "Did they read from different sides?",
    ],
    answerRubric: "Compares group observations; plausible reason for difference; same tools acknowledged.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-sci-energy-forms-storm",
    title: "Name the storm's energy forms",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.P.10.1"],
    chapterId: "u2-ch5",
    unitId: "u2-camp",
    prompt:
      "Identify basic forms of energy: light, heat, sound, electrical, mechanical. Match each to a storm-watch observation. Far lightning is light; we do not stage injuries.",
    scaffoldHints: [
      "Wind moving trees is mechanical (energy of motion).",
      "Thunder is sound.",
      "The radio crackle is electrical.",
    ],
    answerRubric: "Correct identification of the listed energy forms in context.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Thunder is mainly —",
        choices: ["light", "sound", "a kind of plant", "gravity"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "A spinning wind toy on the mast shows —",
        choices: ["mechanical energy", "a fraction", "a primary source", "a haiku"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "Name one heat example and one electrical example at camp during the storm watch.",
        sampleAnswer: "Heat: sun-warmed rock or lamp; electrical: radio/slate.",
      },
    ],
  }),
  a({
    slug: "g3-sci-energy-causes-change",
    title: "Energy that moves or changes",
    kind: "STORY_SCENE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.P.10.2"],
    chapterId: "u2-ch5",
    unitId: "u2-camp",
    prompt:
      "Recognize that energy can cause motion or create change. Pick two camp examples (wind on sailcloth; heat drying a sock). Explain the change.",
    scaffoldHints: [
      "Motion: something starts moving.",
      "Change: temperature, wet to dry, position.",
      "Name the energy, then the change.",
    ],
    answerRubric: "Two examples linking energy to motion or change.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-sci-share-weather-log",
    title: "Why scientists share",
    kind: "CREW_DIALOGUE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.N.1.4"],
    chapterId: "u2-ch5",
    unitId: "u2-camp",
    prompt:
      "Recognize the importance of communication among scientists. Tem wants to hide a scary gust count 'so nobody panics.' Argue, using science norms, why the log must be shared.",
    scaffoldHints: [
      "Other people cannot check what they cannot see.",
      "Sharing is not the same as shouting.",
      "The Guild inspector will ask who saw the numbers.",
    ],
    answerRubric: "States why communication among scientists/scouts matters; log-sharing decision.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-sci-water-states",
    title: "Water changing state at the spring",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.P.9.1"],
    chapterId: "u2-ch6",
    unitId: "u2-camp",
    prompt:
      "Describe changes water undergoes when heating and cooling: melting, freezing, boiling, evaporation, condensation. Use those scientific terms.",
    scaffoldHints: [
      "Ice to liquid is melting.",
      "Liquid to gas at the kettle is boiling; wet clothes drying is evaporation.",
      "Drops on the outside of a cold pot can be condensation.",
    ],
    answerRubric: "Correct term-to-phenomenon matches; observable K–5 level, no molecular lecture required.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Morning ice on a bucket becomes water. This is —",
        choices: ["freezing", "melting", "condensation", "a metaphor"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "Steam from the kettle and a shrinking puddle in sun both show water becoming gas. The puddle is mainly —",
        choices: ["freezing", "evaporation", "melting", "gravity"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "Drops form on the outside of a cold water jar on a warm afternoon. Name the process and why the jar's outside is involved.",
        sampleAnswer: "Condensation; water vapor in air cools on the cold surface and becomes liquid.",
      },
    ],
  }),
  a({
    slug: "g3-sci-plant-structures",
    title: "Label the garden plant's jobs",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.L.14.1"],
    chapterId: "u2-ch6",
    unitId: "u2-camp",
    prompt:
      "Describe structures in plants and their roles: food production, support, water and nutrient transport, reproduction. Match root, stem, leaf, flower (and seed if shown).",
    scaffoldHints: [
      "Leaves help make food (with light).",
      "Roots take in water; they also hold the plant.",
      "Flowers are often about reproduction.",
    ],
    answerRubric: "Correct structure-to-role matches.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-sci-plants-make-food",
    title: "What plants use to make food",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.L.17.2"],
    chapterId: "u2-ch6",
    unitId: "u2-camp",
    prompt:
      "Recognize that plants use energy from the Sun, air, and water to make their own food. The crew cannot 'feed' a plant a biscuit and call it the plant's food-making.",
    scaffoldHints: [
      "Plants make food; animals eat food.",
      "Sun, air, and water are the inputs named in the standard.",
      "Dark closet plants struggle because of missing light energy.",
    ],
    answerRubric: "Correctly names Sun, air, and water as what plants use to make food.",
    storySkinNotes: skin,
    estimatedMinutes: 7,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Plants make their own food using —",
        choices: ["only soil and biscuits", "energy from the Sun, air, and water", "only moonlight", "metal nails"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "A seedling in a dark crate will most likely —",
        choices: ["make food better", "struggle because it lacks light energy from the Sun", "turn into an animal", "freeze the spring"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "Pell says plants 'eat dirt.' Correct Pell using the standard's three inputs.",
        sampleAnswer: "Plants use Sun, air, and water to make food; soil is not the same as those three.",
      },
    ],
  }),
  a({
    slug: "g3-sci-ridge-model",
    title: "Clay ridge as a model",
    kind: "CREATIVE_PROJECT",
    prismaKind: "CHALLENGE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.N.3.2"],
    chapterId: "u3-ch7",
    unitId: "u3-map",
    prompt:
      "Recognize that scientists use models to understand how things work. Build or sketch a clay/ridge model and explain one thing it helps you understand.",
    scaffoldHints: [
      "A model stands for the real thing.",
      "You can test a path on clay without walking the cliff.",
      "Name what the model represents.",
    ],
    answerRubric: "States that models help explain how things work; example is a model, not the real ridge.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-sci-model-limits",
    title: "Where the clay lies",
    kind: "PLAN_WRITING",
    prismaKind: "JOURNAL_PROMPT",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.N.3.3"],
    chapterId: "u3-ch7",
    unitId: "u3-map",
    prompt:
      "Recognize that all models are approximations and do not perfectly account for all observations. List two things the clay ridge fails to show (wind, living plants, true scale, wet rock).",
    scaffoldHints: [
      "Approximation means close, not perfect.",
      "If the real ridge is wet and the clay is dry, that is a miss.",
      "Scale is often wrong on purpose.",
    ],
    answerRubric: "Names limits of the model vs real observations.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-sci-plant-stimuli",
    title: "Stems to light, roots down",
    kind: "STORY_SCENE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.L.14.2"],
    chapterId: "u3-ch8",
    unitId: "u3-map",
    prompt:
      "Investigate and describe how plants respond to stimuli (heat, light, gravity): stems toward light, roots downward. Use the window-box demo. Decide where to set the garden boxes.",
    scaffoldHints: [
      "Turn one box away from light and predict the stem.",
      "Roots grow down even if you tip the pot (gently).",
      "Heat may wilt; that is also a response.",
    ],
    answerRubric: "Describes tropism-like responses; garden placement uses the evidence.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
  }),
  a({
    slug: "g3-sci-seed-vs-spore",
    title: "Seeds or spores?",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.L.15.2"],
    chapterId: "u3-ch8",
    unitId: "u3-map",
    prompt:
      "Classify flowering vs nonflowering plants: seed producers vs ferns and mosses that produce spores, using physical characteristics on the cards.",
    scaffoldHints: [
      "Flowers and seeds go together for many plants.",
      "Ferns and mosses do not make seeds the same way; they make spores.",
      "Use the picture traits, not the cute names.",
    ],
    answerRubric: "Correct seed vs spore classification from characteristics.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-sci-seasonal-change",
    title: "Season signs on the island",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.L.17.1"],
    chapterId: "u3-ch8",
    unitId: "u3-map",
    prompt:
      "Describe how animals and plants respond to changing seasons using Idi's habitat log. Then decide whether to plant the second garden bed now or wait.",
    scaffoldHints: [
      "Look for leaf change, migration, thicker fur, flowering time.",
      "Seasons here are described as the crew's current wet/dry or cool/warm shift — not an exoplanet calendar.",
      "Your planting decision should use a seasonal response.",
    ],
    answerRubric: "Describes plant and animal seasonal responses; decision uses them.",
    storySkinNotes: skin,
    estimatedMinutes: 12,
    readingText:
      "Idi's habitat log. The grove that was full of pale flowers two weeks ago is dropping petals. Birds that hopped the beach at dawn now feed inland at midday. A small mammal's coat looks thicker in the morning chill. Ferns stay green in the wet shade; the flowering vine on the wreck does not. Pell wants to plant now because he is hungry. Mara wants to wait until the cool mornings ease. The log does not say 'winter' or 'summer' by Earth month — it only records change over the weeks we have been here.",
  }),
  a({
    slug: "g3-sci-light-straight",
    title: "Lamp beam in a straight line",
    kind: "STORY_SCENE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.P.10.3"],
    chapterId: "u3-ch9",
    unitId: "u3-map",
    prompt:
      "Demonstrate that light travels in a straight line until it strikes an object or travels from one medium to another. Use the signal lamp, smoke, and a dish of water.",
    scaffoldHints: [
      "Dust or smoke can make the beam visible.",
      "The beam stops being a straight path in air when it hits the mirror or enters water.",
      "Do not stare into the lamp.",
    ],
    answerRubric: "Describes straight-line travel and a change when hitting an object or changing medium.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-sci-reflect-refract-absorb",
    title: "Mirror, water, dark cloth",
    kind: "INTERACTIVE_SORT",
    prismaKind: "INTERACTIVE_GAME",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.P.10.4"],
    chapterId: "u3-ch9",
    unitId: "u3-map",
    prompt:
      "Demonstrate that light can be reflected, refracted, and absorbed. Sort stations: polished metal (reflect), water jar (refract), black cloth (absorb).",
    scaffoldHints: [
      "Reflect: bounces off.",
      "Refract: bends when it goes into a new material (the stick looks 'broken' in water).",
      "Absorb: the cloth takes in light and looks dark.",
    ],
    answerRubric: "Correct match of reflect / refract / absorb to stations.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-sci-light-and-heat",
    title: "The lamp warms your hand",
    kind: "STORY_SCENE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.P.11.1"],
    chapterId: "u3-ch9",
    unitId: "u3-map",
    prompt:
      "Investigate, observe, and explain that things that give off light often also give off heat. Compare the signal lamp, a sunlit stone, and a cold unlit lantern.",
    scaffoldHints: [
      "Hold your hand near, not on, the lamp.",
      "The Sun is a light source that also heats.",
      "An unlit lantern may give neither.",
    ],
    answerRubric: "Observation plus explanation that light sources often emit heat.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-sci-overcome-gravity",
    title: "Catch the falling pulley",
    kind: "STORY_SCENE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.E.5.4"],
    chapterId: "u3-ch9",
    unitId: "u3-map",
    prompt:
      "Explore that gravity is a force that can be overcome. Design a catch, a shelf, or a hand-ready hold so a pulley does not fall to the deck. No one is harmed on screen.",
    scaffoldHints: [
      "Gravity pulls toward the ground.",
      "Overcoming it can mean holding, catching, or supporting.",
      "A net is a way to overcome a fall.",
    ],
    answerRubric: "Recognizes gravity as a downward force and a method to overcome it.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-sci-check-evidence",
    title: "Check each other's explanations",
    kind: "CREW_DIALOGUE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.N.1.5"],
    chapterId: "u4-ch10",
    unitId: "u4-charter",
    prompt:
      "Recognize that scientists question, discuss, and check each other's evidence and explanations. Idi claims the wind 'always' dies at dusk. Tem's log disagrees. Run a civil check.",
    scaffoldHints: [
      "Ask for the data, not for a fight.",
      "Checking might mean looking at more nights.",
      "You can disagree and still be a crew.",
    ],
    answerRubric: "Models questioning and checking evidence; no personal insult.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
  a({
    slug: "g3-sci-science-words",
    title: "Science meaning vs everyday talk",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.N.3.1"],
    chapterId: "u4-ch10",
    unitId: "u4-charter",
    prompt:
      "Recognize that words in science can have different or more specific meanings than everyday language: energy, cell, heat/cold, evidence.",
    scaffoldHints: [
      "Everyday 'energy' might mean 'feeling lively.'",
      "Science 'evidence' is observations/measurements, not 'I feel sure.'",
      "Heat is not the same as 'spicy food.'",
    ],
    answerRubric: "Contrasts everyday vs science meanings for targeted words.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "In science class, evidence is closest to —",
        choices: ["a rumor", "observations or measurements", "a threat", "a poem type"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "Pell says he has 'no energy.' The science meaning of energy is closer to —",
        choices: ["the ability to cause motion or change", "being bored", "a kind of biscuit", "a map scale"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "How is 'cold' in everyday talk different from what a thermometer measures?",
        sampleAnswer: "Everyday cold is a feeling; science uses temperature as a measurement of how hot/cold something is.",
      },
    ],
  }),
  a({
    slug: "g3-sci-friction-heat",
    title: "Rubbing rope makes heat",
    kind: "STORY_SCENE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.P.11.2"],
    chapterId: "u4-ch11",
    unitId: "u4-charter",
    prompt:
      "Investigate, observe, and explain that heat is produced when one object rubs against another (hands, dry rope fibers). Safety: stop if skin hurts.",
    scaffoldHints: [
      "Rub, then feel.",
      "More rubbing, more heat — to a point.",
      "This is not the same as the Sun heating a tin.",
    ],
    answerRubric: "Observation that rubbing produces heat; simple explanation.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
  }),
  a({
    slug: "g3-sci-stars-differ",
    title: "Stars from the tower",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.E.5.1"],
    chapterId: "u4-ch12",
    unitId: "u4-charter",
    prompt:
      "Explain that stars can be different: some smaller, some larger, some appear brighter; all except the Sun are so far they look like points of light. Use the Guild astronomy primer (Earth science) plus what you see.",
    scaffoldHints: [
      "Do not say we are on a secret planet.",
      "Points of light means they look tiny because they are far.",
      "The Sun is the exception in how it looks to us.",
    ],
    answerRubric: "Includes size/brightness differences and point-of-light reason (distance); Sun excepted.",
    storySkinNotes: skin,
    estimatedMinutes: 8,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "Most stars look like points of light because they are —",
        choices: ["made of paper", "very far away", "always smaller than pebbles", "not real"],
        correctIndex: 1,
      },
      {
        itemType: "multiple_choice",
        prompt: "Which star does not look like a tiny point from our camp?",
        choices: ["The Sun", "A dim night star", "A bright night star that is still a point", "The spyglass"],
        correctIndex: 0,
      },
      {
        itemType: "free_response",
        prompt: "Can two stars look different in brightness even if both are points of light? Explain.",
        sampleAnswer: "Yes; stars can appear brighter or dimmer and still look like points because they are far.",
      },
    ],
  }),
  a({
    slug: "g3-sci-sun-is-a-star",
    title: "The Sun emits light",
    kind: "SHIP_LOG_READING",
    prismaKind: "READING",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.E.5.2"],
    chapterId: "u4-ch12",
    unitId: "u4-charter",
    prompt:
      "Identify the Sun as a star that emits energy, some of it as light. After the primer page, decide whether the night watch should treat moonlight as 'the Sun's leftover' or as a different observed light — using only what the page supports.",
    scaffoldHints: [
      "Emit means give off.",
      "The Sun is a star.",
      "Do not invent extra suns.",
    ],
    answerRubric: "Sun identified as a star that gives off energy including light; decision does not contradict the page.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
    readingText:
      "Guild astronomy primer, child plate. The Sun is a star. It gives off energy. Some of that energy is light we see; some we feel as heat on skin. Other stars are also suns to faraway worlds, but they look faint to us. This plate does not discuss moons in detail. It only asks you to remember: our daylight comes from a star, and that star is the Sun.",
  }),
  a({
    slug: "g3-sci-sun-closest",
    title: "Why the Sun looks huge",
    kind: "MINI_QUIZ",
    prismaKind: "MINI_QUIZ",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.E.5.3"],
    chapterId: "u4-ch12",
    unitId: "u4-charter",
    prompt:
      "Recognize that the Sun appears large and bright because it is the closest star to Earth. (The primer is Earth knowledge. Do not 'correct' it with island secrets.)",
    scaffoldHints: [
      "Closest, not 'the only star.'",
      "Appearance can trick you: close can look bigger.",
      "Night stars are still stars.",
    ],
    answerRubric: "States closeness to Earth as the reason the Sun appears large and bright.",
    storySkinNotes: skin,
    estimatedMinutes: 6,
    quizItems: [
      {
        itemType: "multiple_choice",
        prompt: "The Sun looks large and bright mainly because it is —",
        choices: ["the closest star to Earth", "not a star", "made of lightning", "smaller than every night star"],
        correctIndex: 0,
      },
      {
        itemType: "multiple_choice",
        prompt: "A bright night star still looks like a point because —",
        choices: ["it is closer than the Sun", "it is much farther than the Sun", "it is a planet we must name", "points are a kind of fraction"],
        correctIndex: 1,
      },
      {
        itemType: "free_response",
        prompt: "In one or two sentences, explain the Sun's appearance using the word closest.",
        sampleAnswer: "The Sun appears large and bright because it is the closest star to Earth.",
      },
    ],
  }),
  a({
    slug: "g3-sci-spyglass-stars",
    title: "More stars through the spyglass",
    kind: "STORY_SCENE",
    prismaKind: "STORY_SCENE",
    subjectSlug: "science_g3",
    targetStandardCodes: ["SC.3.E.5.5"],
    chapterId: "u4-ch12",
    unitId: "u4-charter",
    prompt:
      "Investigate that the number of stars seen through a telescope is dramatically greater than with the unaided eye. Count (approximately) with eye, then with Tem's spyglass. Do not look at the Sun through it.",
    scaffoldHints: [
      "Same patch of sky.",
      "Dramatically greater means many more, not one extra.",
      "A spyglass is a telescope-like tool.",
    ],
    answerRubric: "Records a much larger count through the tool than by eye.",
    storySkinNotes: skin,
    estimatedMinutes: 10,
  }),
];
